### PR TITLE
Update cample to v3.2.0-beta.6

### PR DESCRIPTION
**Pull request by antonmak1**
Corrected the code a little. I think select row will be a little faster :)

### CODE REVIEW

**Comment by krausest** [comment]
Here's the comparison (left new, right last run) - yes maybe select got a bit faster:
Screenshot 2023-11-24 at 8 02 25 AM

**Comment by krausest** [comment]
Just as a note: Transpilation is mixing up the code anyway. Left your version, on the right the old version:
Screenshot 2023-11-24 at 8 07 58 AM

**Comment by krausest** [comment]
Just noticed I made a mistake. I'll get back tomorrow with updated results.

**Comment by antonmak1** [comment]
> Here's the comparison (left new, right last run) - yes maybe select got a bit faster: Screenshot 2023-11-24 at 8 02 25 AM

Thank you very much! Okay, as you wish. It can be seen that the select row results are still a little better - that’s good! But, I tried to introduce new template processing for the loop, and it can be seen that the results of creating rows have become slower. I'm working on this now, optimizing the new code. I think that before the new year we will be able to achieve a result of 1.08 - 1.09.

**Comment by antonmak1** [comment]
> Just as a note: Transpilation is mixing up the code anyway. Left your version, on the right the old version: Screenshot 2023-11-24 at 8 07 58 AM

Strange, I didn’t change main.js in the new version. I haven’t used Switch case for a long time to process events, maybe 2-3 months. Maybe it's some other main.js?

**Comment by krausest** [comment]
I forgot to git pull before running the benchmark for the updated frameworks. For frameworks that have a real build step (npm run build-prod) there should be no change. But the displayed version for cample was wrong.
 
Nevertheless I ran again (this time after git pull).
Here's the comparison (left new keyed version, right old keyed version):
Screenshot 2023-11-24 at 7 56 16 PM

**Comment by antonmak1** [comment]
Thanks a lot! Yes, this is approximately how the results are on my computer now. I was just thinking today why select row is bigger. Happens.

**Pull request merged**
