### PR TITLE
Update sifrr to 0.0.2

### PR DESCRIPTION
**Pull request by aadityataparia**

### CODE REVIEW

**Comment by krausest** [comment]
Sorry, can't merge it in its current state since CSS styles are broken.
Please make sure to use the stylesheet from "/css/currentStyle.css" (and that the correct font is applied).
bildschirmfoto 2019-02-07 um 20 59 00

**Comment by aadityataparia** [comment]
Sorry forgot to add glyphicons! 🙇

**Comment by aadityataparia** [comment]
Can you please check now? 🙏

**Comment by krausest** [comment]
Thanks - I‘ll take a look at it tomorrow!

**Comment by krausest** [comment]
CSS looks fine now, but selecting a row and removing a row doesn't work for me.

**Comment by aadityataparia** [comment]
Sorry for bothering you! Should be fixed now, let me know if there are any other problems! 🙇

**Comment by krausest** [comment]
Not bad. Does it also support keyed updates?
bildschirmfoto 2019-02-18 um 21 23 35

**Comment by krausest** [comment]
Seems like sifrr violates the (new) rule "...the initial rendering is able to render the selection state"
Can you please take a look at the last bullet point in how to contribute and check your implementation?

**Comment by aadityataparia** [comment]
> Not bad. Does it also support keyed updates?

@krausest Not yet, maybe in future 🙇 

> ...the initial rendering is able to render the selection state

Oh, let me check. Thanks

**Comment by aadityataparia** [comment]
> ...the initial rendering is able to render the selection state

Got it, will open a PR! 👍

**Pull request merged**
