### PR TITLE
Update lit-html to 1.0.0

### PR DESCRIPTION
**Pull request by CaptainCodeman**
Released !

### CODE REVIEW

**Comment by krausest** [comment]
Congrats! Here are the keyed results:
bildschirmfoto 2019-02-06 um 20 34 54

**Comment by CaptainCodeman** [comment]
Sweet - thank you !

**Comment by krausest** [comment]
@CaptainCodeman All results have been updated for Chrome 72. What's a bit puzzling is that Chrome 72 is significantly faster for create and replace while relative ranking for lit-html seems rather stable...

**Comment by CaptainCodeman** [comment]
Thanks - I'll take a look into it and see if I can find out why.

**Pull request merged**
