### PR TITLE
VanillaJS-3 implementation

### PR DESCRIPTION
**Pull request by mksunny1**
I still attempted an implementation that was faster for creating 1K rows. I could not go faster here. However, I found consistent gains in other areas.

Screenshot 2024-05-10 at 13 55 50

Screenshot 2024-05-10 at 13 56 08

Screenshot 2024-05-10 at 13 56 16

Screenshot 2024-05-10 at 13 56 24

### CODE REVIEW

**Comment by leeoniya** [comment]
probably you should test against `vanillajs-light`, which is much faster than the others.

https://github.com/krausest/js-framework-benchmark/pull/1666

**Comment by mksunny1** [comment]
@leeoniya not exactly. Have you seen the results preview?

**Comment by krausest** [comment]
There was a conflict. I resolved it using this version.
I hope to publish results for the PR tomorrow.

**Comment by krausest** [comment]
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are up and it looks good for vanillajs-3 and vanillajs-lite. I guess there's too much vanilla now and I'll retire the others.

**Comment by mksunny1** [comment]
Wow, this is amazing. The earlier implementations are great for reference, history, and variety. VanillaJS-3 is mostly syntax sugar for VanillaJS with some purposeful performance tweaks.

**Comment by mksunny1** [comment]
I am adding async and defer attributes to the script tag (to improve first paint time) and minor changes to the script file. Just cleaning up the code...

**Comment by mksunny1** [comment]
First-paint time suffered after adding the tags. I will complete my experimentation and push any useful changes. I want to ask but I think it may be silly to actually ask if you measure the time for the initial script run to complete. I am guessing the answer is 'yes'.

**Pull request merged**
