### PR TITLE
Doo html v0.91.1 beta keyed

### PR DESCRIPTION
**Pull request by hman61**

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Maybe it's not just noise and really a bit faster than the old version:
Bildschirm­foto 2023-03-04 um 22 54 18

**Comment by krausest** [comment]
BTW that append to many rows looks interesting. What are you doing differently to all other implementations?

**Comment by krausest** [comment]
Ok. I found it:
Bildschirm­foto 2023-03-04 um 23 14 26
The test driver only checks that a <tr> is found, it doesn't check the contents.
Can you fix that please?

**Comment by hman61** [comment]
I will try to get that fixed ASAP, no wonder why I ended up #1 in that
category LOL

**Comment by hman61** [comment]
I have a fix for the append issue in DooHTML - keyed

https://github.com/krausest/js-framework-benchmark/pull/1199

**Pull request merged**
