### PR TITLE
Qwik

### PR DESCRIPTION
**Pull request by wmertens**
Based on #1101

### CODE REVIEW

**Comment by krausest** [comment]
Great thanks - I'm very excited to see qwik.

I tried to run it, but it failed to served correctly from the server in the root dir.
The index.html from `npm run build-prod` can't load its files due to a wrong url:
Screenshot 2023-10-21 at 4 37 53 PM
The url they could be accessed is something like http://localhost:8080/frameworks/keyed/qwik/dist/build/build/...
Can you please fix the URL handling?
(And from what I've seen we should load the css instead of include it in the bundle)

BTW the build dir in dist looks a bit redundant:
```
ls -l dist/
total 88
-rw-r--r--  1 stefan  staff    759 Oct 21 16:33 404.html
drwxr-xr-x  9 stefan  staff    288 Oct 21 16:36 build
-rw-r--r--  1 stefan  staff   5951 Oct 21 16:33 index.html
-rw-r--r--  1 stefan  staff     97 Oct 21 16:33 q-data.json
-rw-r--r--  1 stefan  staff  19412 Oct 21 16:33 q-manifest.json
-rw-r--r--  1 stefan  staff   3595 Oct 21 16:33 service-worker.js
-rw-r--r--  1 stefan  staff    158 Oct 21 16:33 sitemap.xml
ls -l dist/build
total 88
-rw-r--r--   1 stefan  staff    759 Oct 21 16:36 404.html
drwxr-xr-x  29 stefan  staff    928 Oct 21 16:36 build
-rw-r--r--   1 stefan  staff   5951 Oct 21 16:36 index.html
-rw-r--r--   1 stefan  staff     97 Oct 21 16:36 q-data.json
-rw-r--r--   1 stefan  staff  19412 Oct 21 16:36 q-manifest.json
-rw-r--r--   1 stefan  staff   3595 Oct 21 16:36 service-worker.js
-rw-r--r--   1 stefan  staff    158 Oct 21 16:36 sitemap.xml
ls -l dist/build/build
total 952
-rw-r--r--  1 stefan  staff     933 Oct 21 16:36 q-0b7f4460.js
-rw-r--r--  1 stefan  staff    5614 Oct 21 16:36 q-0bba13e6.js
-rw-r--r--  1 stefan  staff    1149 Oct 21 16:36 q-11bea4ba.js
-rw-r--r--  1 stefan  staff     671 Oct 21 16:36 q-132510b4.js
...
```

**Comment by wmertens** [comment]
@krausest ok I removed the css importing and fixed the URL. I can't make the benchmark work because playwright isn't cooperating due to library issues. But when I run `npx serve .` from the project root I can go to the qwik/dist dir and it finds everything.

As for the build, it's very odd, for me the build dir looks like this:

```
 $ tree dist
dist/
|-- 404.html
|-- build/
|   |-- q-0fa0a040.js
|   |-- q-18a98fc1.js
|   |-- q-1918ca9f.js
|   |-- q-1a51b947.js
|   |-- q-2065792c.js
|   |-- q-3174fd4d.js
|   |-- q-3884cd5b.js
|   |-- q-3d03bd4b.js
|   |-- q-4403e527.js
|   |-- q-4c13705d.js
|   |-- q-4dc05a1a.js
|   |-- q-4f09e785.js
|   |-- q-551ee945.js
|   |-- q-640d5b4e.js
|   |-- q-663033b0.js
|   |-- q-7927ec9c.js
|   |-- q-b00b37ac.js
|   |-- q-b7db3738.js
|   |-- q-be99f368.js
|   |-- q-dbaf7ab9.js
|   `-- q-e4891997.js
|-- index.html
|-- q-data.json
|-- q-manifest.json
|-- service-worker.js
`-- sitemap.xml

2 directories, 27 files
```

I'm building on Linux, and you?

**Comment by krausest** [comment]
Thanks. CSS looks fine. I usuallly build on a linux VPS. Since I wanted to see if I could fix the issues above I built on osx, which is where the ls commands were issued. On linux the build directory looks fine so feel free to ignore it.

But I'm afraid to say, the base URL doesn't work correctly.
Screenshot 2023-10-21 at 8 18 51 PM
The last line occurs when I click on the create 1,000 rows button.
I can see there's a base="/frameworks/keyed/qwik/dist" now on the html tag, but seems like that's not enough.
I built via `npm run build-prod`

**Comment by wmertens** [comment]
@krausest does it work when you do `npx serve .`? 

Can you check if the package.json is correct? Perhaps I shouldn't have added that dist dir setting?

**Comment by krausest** [comment]
Yes, `npx serve . ` works in the root directory of js-frameworks-benchmark.

Chrome shows that ths js files are loaded via URLs like http://localhost:3000/build/q-a519d965.js which works (though I don't understand why) for `npm serve .` .
Those JS files should be loaded from http://localhost:3000/frameworks/keyed/qwik/dist/build/q-a519d965.js and so on such that it can work for our server (actually port 8080, but this isn't the issue we're working on now).
Screenshot 2023-10-21 at 11 05 29 PM

**Comment by krausest** [comment]
Now this is really weird (or some service worker magic?). If I force a page reaload with Shift+reload button (i.e. invalidate the browser cache), it doesn't work:
Screenshot 2023-10-21 at 11 12 44 PM
If I reload the page afterwards it works again until I make a Shift+Reload.

**Comment by krausest** [comment]
The `npm start` shows one more error in console that `npx serve` doesn't. 
It fails to load http://localhost:8080/service-worker.js.
How can we load the service worker from http://localhost:3000/frameworks/keyed/qwik/dist/service-worker.js? Why isn't that URL accessed  for `npx serve` ?

**Comment by wmertens** [comment]
I'm still not able to run the benchmarks myself, but now the build works with `npx serve .` from the root.

**Comment by wmertens** [comment]
@krausest I think this can be merged - the runtime performance is not what I hoped but at least it gives us something to work towards, and as expected the startup performance is great.

**Comment by krausest** [comment]
Thanks, this works now with one exception: The isKeyed test fails:
```
npm run isKeyed -- --headless true keyed/qwik
Keyed test for create rows failed. Expected that 1000 TRs should be removed and added, but there were 0 added TRs and 0 were removed
Keyed test for remove failed. Expected that the dom node for the 2nd row would be removed, but it wasn't
qwik-v1.2.17-keyed is non-keyed for 'run benchmark' and non-keyed for 'remove row benchmark' and keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
ERROR: Framework qwik-v1.2.17-keyed is not correctly categorized
```
I don't fully understand yet why the test fails and it looks to me like qwik was indeed keyed (usually manually setting the background color of a TR is a easy way to identify non-keyed implementation, but that looks good). Any idea why the test fails? I'll merge this PR and we'll track it in a separate issue (#1496).

**Pull request merged**
