### PR TITLE
Update cample to v.3.2.0-alpha.12

### PR DESCRIPTION
**Pull request by antonmak1**
Hello! I hope the framework will have time to get into the results for version 122. In general, this pr I am 99.99999% sure that it will be 1.09 or lower!

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. I'll try to post results tomorrow.

**Comment by krausest** [comment]
Meanwhile chrome 122 was released. So it'll be included in the chrome 122 results soon.

**Comment by antonmak1** [comment]
Ok

**Comment by krausest** [comment]
Now they're available: https://krausest.github.io/js-framework-benchmark/2024/table_chrome_122.0.6261.69.html

**Comment by antonmak1** [comment]
Really 1.10 again)

**Comment by krausest** [comment]
I swear I didn't do any additional runs until I achieved that result 😄

**Comment by antonmak1** [comment]
Yes, I understand that the problem is in the framework code, but somehow I seem to improve it, but it doesn’t go any further. Well, it happens. The main thing is that select row has become at least a little more decent, otherwise it was generally terribly slow. But this is still a crappy result. Well, I will try to finish it to a normal result. I'm confident that the framework's syntax will allow it to reach less than 1.06 with quality code changes. I understand in theory how to do this, but somehow I already implement a couple of ideas, and then I forget for a while, then again ideas come and I implement.

**Pull request merged**
