### PR TITLE
Added literaljs nonkeyed to frameworks

### PR DESCRIPTION
**Pull request by Mikeysax**
This PR adds LiteralJS nonkeyed.

This is in reference to issue https://github.com/krausest/js-framework-benchmark/issues/545

### CODE REVIEW

**Comment by krausest** [comment]
That merge isn't easy...
Could you please update your package.json like that?
```
       "version": "1.0.0",
        "description": "Benchmark for LiteralJS framework",
        "js-framework-benchmark": {
-               "frameworkVersionFromPackage": "literaljs"
+               "frameworkVersionFromPackage": "literaljs",
+               "customURL": "/dist"
        },
        "main": "index.js",
        "scripts": {
                "start": "parcel index.html",
                "dev": "parcel index.html --open",
-               "build-prod": "NODE_ENV=production parcel build index.html --no-minify --public-url /",
+               "build-prod": "NODE_ENV=production parcel build index.html --no-minify --public-url /frameworks/non-keyed/literaljs/dist/",
                "test": "echo \"Error: no test specified\" && exit 1"
        },
```
I could open `http://localhost:8080/frameworks/non-keyed/literaljs/dist/` after that.
Sadly I haven't found a fix for an issue with the clear button. Click create 1,000 rows and then clear. The first row stays on the screen. (The store implementation looks fine though).
Can you please take a look at it?

**Comment by Mikeysax** [comment]
@krausest Thanks for that! 

I made the following changes you mentioned and also soft fixed the bug where a row is still shown after clearing the state.

**Comment by krausest** [comment]
It worked that way! I'm afraid to say but it seems it's one of the slower non-keyed frameworks.
Results were updated. Here's a screenshot:
Bildschirmfoto 2019-04-14 um 14 29 04

**Comment by Mikeysax** [comment]
@krausest Thanks! It's interesting to see what it does well and what I could improve performance wise.

**Pull request merged**
