### PR TITLE
Reflex dom v0.4 keyed

### PR DESCRIPTION
**Pull request by alexfmpe**
~[Working build](https://circleci.com/gh/alexteves/js-framework-benchmark/38) (from another branch with extra commits to compile from source and skip other frameworks since I can't get master to run tests - see #239)~

The benchmark has changed a bit since #214 and was meanwhile added to a branch of [reflex-dom's repo](https://github.com/reflex-frp/reflex-dom/blob/fast-weak-partial-requester/reflex-dom/benchmarks/krausest.hs).

`npm install` checks out the benchmark's source and build system
`npm run build-prod` is a no-op
`npm run build-prod-force` will recompile from source

The thing I'm most unhappy about is that the benchmark source/build files aren't actually added to this repo. Some alternatives to discuss:

1. keep it as it is
2. add the framework as a git submodule/git subtree (don't really have experience with these)
3. duplicate the upstream benchmark into the PR

Number 3 is not DRY and more work when updating, but it's also the simplest.

I'm working with reflex-dom's author @ryantrinkle to add the benchmark to the framework's CI, so it's possible that the compiled files eventually also get extracted out and linked to (unless we pick number 2). Regardless, this will probably take a while.

FWIW, these are the results I got locally from running the tests with `--count 1`
image

### CODE REVIEW

**Comment by krausest** [comment]
I‘m on holidays this and next week - I‘ll take a look at it in two weeks.

**Comment by krausest** [comment]
I'd prefer `npm install` to also be a no-op and have a separate `npm install-force`. This would allow the install.js script to work unchanged. Is that ok for you? Can you update the pull request?

**Comment by alexfmpe** [comment]
For some reason I put the dependency-fetch part in `npm run build-prod-force`, which makes `npm install` just a glorified `git clone`. 
I'll move that part to `npm (run) install-force` tomorrow or so. 
Also have to merge some small improvements from another branch (like the preload icon)

**Comment by alexfmpe** [comment]
Applied requested changes. Should I squash this branch?

There are some improvements (benchmark and build) coming in the next weeks/months, but they're waiting for some CI work on reflex itself.

**Comment by krausest** [comment]
Finally! It even found a bug in webdriverAccess.
The results for reflex dom can be found [here](https://rawgit.com/krausest/js-framework-benchmark/1a56e8c286c1a3b24aca9d48d1d47d88a60f8f89/webdriver-ts-results/table.html).

**Comment by saurabhnanda** [comment]
Awesome 👍

**Comment by saurabhnanda** [comment]
And reflex is not the slowest :)

**Comment by ryantrinkle** [comment]
@saurabhnanda Thanks for helping push this through!  It's clear we've got some weak spots, but I'm pretty pleased with some of the results, e.g. swap rows and remove row.  We'll keep improving from here!

**Comment by alexanderkjeldaas** [comment]
I think this should include a round of closure

I'm using this:

```
CLOSURE_FLAGS    = --compilation_level=ADVANCED_OPTIMIZATIONS --jscomp_off=globalThis \
                   --jscomp_off=suspiciousCode --jscomp_off=uselessCode
 closure-compiler $(CLOSURE_FLAGS) \
           $(shell (stack path --local-install-root))/bin/krausest.jsexe/all.js > ../../../dist/all.js
```

**Comment by saurabhnanda** [comment]
@ryantrinkle thanks for supporting @alexfmpe while was working on this. And great to see that some of these benchmarks have been adopted into Reflex's build-chain as well.

😄

**Comment by ryantrinkle** [comment]
@saurabhnanda It was my pleasure; I'm glad we were able to get something in place that not only helped answer your questions, but will serve as a useful part of our infrastructure going forward.  I'm hoping we can get performance testing integrated into our CI soon, which will really help when evaluating PRs.

**Pull request merged**
