### PR TITLE
feat(angular): rename projects for better report readability

### PR DESCRIPTION
**Pull request by meeroslav**
This PR consists of the following changes:
* All keyed angular projects updated to v11
* Closure projects updated to the latest `google closure compiler` and `rollup` for dev
* Dev serve for rollup fixed, you can now run your rollup projects in dev mode
* Titles and folders renamed to match the intent `angular-{closure}-{nozone}`
* `PlatformBrowserDynamic` replaced with `PlaformBrowser` as there are no dynamic components

### CODE REVIEW

**Comment by krausest** [comment]
I'm planning to remove the angular 8 implementations, since we should focus on the current version. Sadly so far I failed to create an angular 11 closure build. Do you have any pointers or can you contribute such an implementation (the regular "angular-closure" one would suffice) ?

**Comment by meeroslav** [comment]
I will migrate two closure projects to ng11, hopefully in a few days. Sorry for the late reply.

**Comment by krausest** [comment]
That sounds great!

**Comment by krausest** [comment]
Thanks, but the closure builds do not work properly on my machine. Can you please take a look at it?
```
zone.min.js:21 Unhandled Promise rejection: R3InjectorError(lk)[Hk -> zk -> Bj -> InjectionToken Application Initializer -> InjectionToken Application Initializer -> InjectionToken Application Initializer]: 
  NullInjectorError: No provider for InjectionToken Application Initializer! ; Zone: <root> ; Task: Promise.then ; Value: NullInjectorError: R3InjectorError(lk)[Hk -> zk -> Bj -> InjectionToken Application Initializer -> InjectionToken Application Initializer -> InjectionToken Application Initializer]: 
  NullInjectorError: No provider for InjectionToken Application Initializer!
    at Sg.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:157:226)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:54:430)
    at O (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:55:51)
    at Xc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:55:456)
    at Object.d [as g] (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:168:360)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:160:430)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:54:430) NullInjectorError: R3InjectorError(lk)[Hk -> zk -> Bj -> InjectionToken Application Initializer -> InjectionToken Application Initializer -> InjectionToken Application Initializer]: 
  NullInjectorError: No provider for InjectionToken Application Initializer!
    at Sg.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:157:226)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:161:153)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:54:430)
    at O (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:55:51)
    at Xc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:55:456)
    at Object.d [as g] (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:168:360)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:160:430)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure/dist/bundle.js:54:430)
```

```
bundle.js:157 Uncaught (in promise) NullInjectorError: R3InjectorError(lk)[Hk -> zk -> Bj -> InjectionToken Application Initializer -> InjectionToken Application Initializer -> InjectionToken Application Initializer]: 
  NullInjectorError: No provider for InjectionToken Application Initializer!
    at Sg.get (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:157:226)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:161:153)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:161:153)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:54:430)
    at O (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:55:51)
    at Xc (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:55:456)
    at Object.d [as g] (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:168:360)
    at bh.get (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:160:430)
    at Wc (http://localhost:8080/frameworks/keyed/angular-closure-nozone/dist/bundle.js:54:430)
```

**Comment by meeroslav** [comment]
Can you tell me what OS and node version you use?

**Comment by krausest** [comment]
The error happens on Fedora 33 (on my notebook, both with node 14.13.0 and node 15.7.0) and in the docker container with an Ubuntu 20.10 (node 14.4.0).

**Comment by meeroslav** [comment]
The problem is with Closure `ADVANCED_OPTIMIZATIONS`/ Typescript 3.9+ incompatibility.

The support for the Closure compiler in Angular packages has been broken for quite some time. As of TS3.9 Closure is unusable with the JavaScript emit. Please follow [microsoft/TypeScript#38374](https://github.com/microsoft/TypeScript/issues/38374) for further developments.

Meanwhile, I have switched to using `SIMPLE_OPTIMIZATIONS`, but this way we lose the granular tree shaking and qualification. Unless this gets resolved fast on the TS side, I'd recommend removing the two `closure` projects.

**Comment by krausest** [comment]
Thanks - that's very interesting. I wouldn't have thought that closure performs so poor with SIMPLE_OPTIMIZATIONS.

I'll remove the closure versions.

**Pull request merged**
