### PR TITLE
Revert "trying to fix circleci"

### PR DESCRIPTION
**Pull request by alexfmpe**
This reverts commit e8df2a52b3cb4a5213d97c9065da8043de04cb2f.

### CODE REVIEW

**Comment by krausest** [comment]
@alexfmpe 
With the changes reverted the circleci build fails with a timeout:
https://circleci.com/gh/krausest/js-framework-benchmark/317
It passes when running just a single benchmark for each framework. Any suggestions?

**Comment by alexfmpe** [comment]
Strange, given that it built normally in
https://circleci.com/gh/krausest/js-framework-benchmark/314
https://circleci.com/gh/alexfmpe/js-framework-benchmark/157
https://circleci.com/gh/alexfmpe/js-framework-benchmark/162

It could be one of those random chromedriver errors - it doesn't freeze in the same place across runs.

**Comment by alexfmpe** [comment]
How about adding a timeout for each test and at the end re-run only the ones that failed?

**Comment by krausest** [comment]
Don't you think it's just circleci killing the build process due to the whole build duration? (I suspect it kills it after 5 hours).
I just restarted the circleci build - let's see where and when it fails next time.

**Comment by krausest** [comment]
... which was a bad example, since reagent build failed (downloading failure: Could not find artifact org.clojure:google-closure-library:jar:0.0-20170809-b9c14c6b in clojars (https://repo.clojars.org/)) - next attempt.

**Comment by alexfmpe** [comment]
After a closer look, I'm seeing two symptoms.

From [build 266](https://circleci.com/gh/krausest/js-framework-benchmark/266) onwards and until https://github.com/krausest/js-framework-benchmark/commit/e8df2a52b3cb4a5213d97c9065da8043de04cb2f, circleci failed with 
`Too long with no output (exceeded 10m0s)`. Seemed to happen randomly, but I haven't seen it since, presumably caused & fixed by chromedriver updates.
This is what I assumed was still happening, but we're getting a global timeout, not a idleness one.

Builds after #384, test all benchmarks and take just a [bit under two hours](https://circleci.com/gh/krausest/js-framework-benchmark/tree/master). AFAICT the five hours builds started with the commit that forks the benchmark runner. It doesn't hang and continuously produces output - it's just very slow.

**Pull request merged**
