### PR TITLE
lighterhtml: update test using the domc implementation

### PR DESCRIPTION
**Pull request by WebReflection**
As I've found _domc_ implementation both clean and elegant, and as I wanted to also cleanup the previous test, I'd like to update current _hyperhtml_ test which also slightly improves the select row performance.

Thanks for your patience, and the eventual update, I promise this time I've already tested current changes and everything runs smoothly.

Best Regards.

### CODE REVIEW

**Comment by WebReflection** [comment]
as I'd like to land also _neverland_ benchmark, is there, or there will be, any progress with this?

**Comment by krausest** [comment]
Yes, absolutely. Just a lack of time, sorry for that. Hopefully I can merge it the next few days.

**Comment by krausest** [comment]
Finally! Results are [here](https://krausest.github.io/js-framework-benchmark/current.html).

**Comment by WebReflection** [comment]
LOL, things apparently got worse for lighterhtml 😂

Anyway, thanks for updating results and merging this 👍

**Pull request merged**
