### PR TITLE
add kr-observable

### PR DESCRIPTION
**Pull request by nihil-pro**

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. I'm not sure how soon I can perform an incremental run and update the results. I'll comment here when done.

**Comment by krausest** [comment]
Sooner than expected. Here's the comparison (vanilla and vanillajs-3 look OK for an incremental run) with the new / updated results on the left and the old version on the right (so it's not relevant to you):
Screenshot 2024-11-11 at 08 11 41
I guess that partial update, swap and select row do a full update. Maybe you can optimize that.

**Comment by nihil-pro** [comment]
I am thinking about it. It seems that the problem is in the Proxy([]), I tested locally just wrapping the array in a proxy, and the result is not much better. Thanks

**Comment by nihil-pro** [comment]
Screenshot 2024-11-16 at 21 29 26
Screenshot 2024-11-16 at 21 29 54
Done ))
Now is fast enough

**Pull request merged**
