### PR TITLE
Update RE:DOM to 3.14

### PR DESCRIPTION
**Pull request by pakastin**
- Swap rows should be way faster now!
https://github.com/redom/redom/releases/tag/v3.14.0

### CODE REVIEW

**Comment by pakastin** [comment]
Hmm.. that test seems to fail in some other framework.. 🤔

**Comment by pakastin** [comment]
CI test seems to fail in `react-easy-state` before even getting to RE:DOM.. Should work alright!

**Comment by solkimicreb** [comment]
It fails the build process, which should be exactly matching with the other react implementations if I remember correctly. I will check what's the issue. (I am maintaining easy-state)

**Comment by solkimicreb** [comment]
Fixed here: https://github.com/krausest/js-framework-benchmark/pull/466. Lets hope it passes.

**Comment by pakastin** [comment]
Ok thanks, let’s hope so! 🤞

**Comment by krausest** [comment]
Results are up now. Here's a (cross browser versions, OS versions) comparison with the older versions:
bildschirmfoto 2018-10-04 um 21 28 35
Nice speedup for swap rows!

**Comment by pakastin** [comment]
Oh yeah! 🤘

**Pull request merged**
