### PR TITLE
Update sauron to v0.61.4

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by flosse** [comment]
@ivanceras if it is possible for you to publish v0.61.2 on crates.io, I can still update it :smiley:

**Comment by ivanceras** [comment]
@flosse I just released [`sauron@0.61.3`](https://crates.io/crates/sauron).

BTW, I intend to use the [`use-template`](https://github.com/ivanceras/sauron/blob/master/examples/js-performance-benchmark-sauron/src/lib.rs) feature in sauron for the benchmark, but there
are still some minor issues I have to iron-out.

**Comment by flosse** [comment]
> @flosse I just released [`sauron@0.61.3`](https://crates.io/crates/sauron).

:+1:  

I force-pushed this PR now.

> BTW, I intend to use the [`use-template`](https://github.com/ivanceras/sauron/blob/master/examples/js-performance-benchmark-sauron/src/lib.rs) feature in sauron for the benchmark, but there are still some minor issues I have to iron-out.

Cool, I'll have a look at that when I get the time.

**Comment by krausest** [comment]
Here's a comparison (updated keyed results on the left, old results on the right). Looks a bit slower...
Screenshot 2024-04-13 at 21 55 21

**Comment by ivanceras** [comment]
@krausest it's a good tradeoff for making the code more elegant and simpler. Maybe I'll focus on performance on next releases.

**Pull request merged**
