### PR TITLE
Update svelte to 5.0.0-next.174

### PR DESCRIPTION
**Pull request by trueadm**
There were some bugs in Svelte 165 that affected performance, they should be fixed in this update.

### CODE REVIEW

**Comment by krausest** [comment]
Thanks - I'll post the results tomorrow.

**Comment by krausest** [comment]
The [results](https://krausest.github.io/js-framework-benchmark/current.html) are updated (left updated keyed results, right old results). svelte-classic is a bit slower, but it's within the range of noise.
Screenshot 2024-07-05 at 07 37 07

**Comment by trueadm** [comment]
@krausest That's strange. I get very different results locally – with 174 being significantly faster than before.

**Comment by krausest** [comment]
I took another look at it just to check if I made some mistake or my update scripts wouldn't work right. So I created two new versions with just the package.json adjusted to .165 and .174, built the two and ran them together with the unchanged keyed/svelte version (i.e. also .174). 
I confirmed that the shasum of main.js in keyed/svelte and keyed/svelte-174 was identical and differed from keyed/svelte-165, so I'm quite confident that I didn't mix up versions. Here's the result on my machine (performance looks completely identical for the three versions):
Screenshot 2024-07-10 at 18 33 43 

The package-lock of .165 looks like that:
```
"node_modules/svelte": {
      "version": "5.0.0-next.165",
      "resolved": "https://registry.npmjs.org/svelte/-/svelte-5.0.0-next.165.tgz",
      "integrity": "sha512-r/dr89AAzIsT/tpIJsenhkWjJ7j2Q1Q3tdPu2qgi/8Vc42dtvHPr1XHn9qJhjXIGVE/cS1BxEuwG+Qwp7YUqkw==",
```

Can you post a screenshot of the results on your machine? What are the specs of your machine?

**Comment by trueadm** [comment]
I notice that in my runs I get far more variance on all the test cases (select row is +- 1.1). I'm running an M2 Max with 32GB RAM + Chrome 126. So that is probably why the numbers might be off for me. The variance never used to be that bad in earlier versions of Chrome either :/

**Comment by krausest** [comment]
Just to make sure: Is the testdriver up to date and was it built recently (i.e. after chrome 124)? 
(if not => `npm run compile` in webdriver-ts)

**Comment by trueadm** [comment]
@krausest I'll do that and re-run the benchmarks for both and also the other frameworks.

**Comment by trueadm** [comment]
Screenshot 2024-07-10 at 18 42 26

You were right, after updating webdriver-ts, there's almost nothing in it. Interestingly though the overalls core is considerably different from yours and also in comparison to the other frameworks. I assume the scores will normalise out when you do the next browser update?

**Comment by krausest** [comment]
That's good!
This is something I have no good explanation. Incremental runs (just the updated frameworks + vanillajs) tend to perform worse than full runs. I eliminated minor browser updates by switching to a fixed chrome for testing version, I'm stopping onedrive and I'm quitting all apps whenever I'm running the benchmark.
For a full run I'm also rebooting before running and I guess there are less background processes (like karabiner elements, betterdisplay, etc. won't be started), but I'm not sure what is guilty here. Seems to have become worse since a few months.
The last [full run ](https://krausest.github.io/js-framework-benchmark/2024/table_chrome_126.0.6478.55.html ) was closer to your results. So I indeed hope that results look better in a full run.

P.S. I'm surprised the absolute numbers from the full run for my M1 are so close to your M2.

**Comment by krausest** [comment]
If you want to read more about the chrome 124 issue, this is a good start: https://github.com/krausest/js-framework-benchmark/issues/1661#issuecomment-2099578793

**Comment by trueadm** [comment]
@krausest M1 and M2s are sensitive to temperature. I have a window near my Mac which helps keep it cool. If I close my window and its warm outside, the results jump all over the place pretty quickly (you can use a core speed tracker).

**Comment by krausest** [comment]
I'll have to keep an eye on that. When I had a MacBook Air M1 I looked at powermetrics: https://github.com/krausest/js-framework-benchmark/issues/885#issuecomment-841810772 but didn't find signs of throttling (at least that way).
Maybe I'll take a look at Mx Power Gadget. What do you use to find out about throttling?

**Pull request merged**
