### PR TITLE
added react-mlyn keyed implementation

### PR DESCRIPTION
**Pull request by vaukalak**
This is benchmark for `react-mlyn` framework https://github.com/vaukalak/react-mlyn

### CODE REVIEW

**Comment by krausest** [comment]
Sorry, but the build fails with the following error. Can you please take a look at it?
```
> js-framework-benchmark-react-mlyn@1.0.0 build-prod /build/frameworks/keyed/react-mlyn
> webpack

Hash: 82f55bba0f9385c33d6b
Version: webpack 4.34.0
Time: 1235ms
Built at: 01/15/2022 6:24:16 PM
  Asset     Size  Chunks             Chunk Names
main.js  206 KiB    main  [emitted]  main
Entrypoint main = main.js
[./src/main.jsx] 13.6 KiB {main} [built]
    + 15 hidden modules

ERROR in ./node_modules/react-dom/cjs/react-dom.production.min.js
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/node_modules/react-dom/cjs'
 @ ./node_modules/react-dom/cjs/react-dom.production.min.js 12:20-36
 @ ./node_modules/react-dom/index.js
 @ ./src/main.jsx

ERROR in ./node_modules/react-mlyn/lib/hooks.js
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/node_modules/react-mlyn/lib'
 @ ./node_modules/react-mlyn/lib/hooks.js 8:13-29
 @ ./node_modules/react-mlyn/lib/index.js
 @ ./src/main.jsx

ERROR in ./node_modules/react-mlyn/lib/utils.js
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/node_modules/react-mlyn/lib'
 @ ./node_modules/react-mlyn/lib/utils.js 10:37-53
 @ ./node_modules/react-mlyn/lib/index.js
 @ ./src/main.jsx

ERROR in ./node_modules/react-mlyn/lib/dom.js
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/node_modules/react-mlyn/lib'
 @ ./node_modules/react-mlyn/lib/dom.js 8:36-52
 @ ./node_modules/react-mlyn/lib/index.js
 @ ./src/main.jsx

ERROR in ./node_modules/react-mlyn/lib/components.js
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/node_modules/react-mlyn/lib'
 @ ./node_modules/react-mlyn/lib/components.js 10:37-53
 @ ./node_modules/react-mlyn/lib/index.js
 @ ./src/main.jsx

ERROR in ./src/main.jsx
Module not found: Error: Can't resolve 'react' in '/build/frameworks/keyed/react-mlyn/src'
 @ ./src/main.jsx 42:0-41 107:2-11 199:2-11

ERROR in ./src/main.jsx
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/build/frameworks/keyed/react-mlyn/src'
 @ ./src/main.jsx 45:0-48 46:0-50 93:26-30 95:31-35 129:26-30 131:31-36 133:34-38 135:35-39 138:27-31 140:35-40 142:38-42 150:31-35 158:31-35 166:31-35 174:31-35 182:31-35 289:22-27 291:28-32 293:21-25 295:29-33 296:31-35 305:32-37 307:38-42 311:31-35 313:39-43 319:31-35 321:39-43 325:41-45 330:31-35 337:21-25 344:21-25
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! js-framework-benchmark-react-mlyn@1.0.0 build-prod: `webpack`
npm ERR! Exit status 2

```

**Comment by vaukalak** [comment]
@krausest sorry for that. should be fixed now.

**Comment by krausest** [comment]
It builds fine now, but it isn't keyed by our definition. Seems like swap and replace all reuse the existing dom elements.
Here'ss the result of `npm run isKeyed keyed/react-mlyn`:
```
Keyed test for swap failed. Expected at least 1 added and 1 removed TR, but there were 0 added and 0 removed
Keyed test for create rows failed. Expected that 1000 TRs should be removed and added, but there were 0 added TRs and 0 were removed
react-mlyn-v0.5.9-keyed is non-keyed for 'run benchmark' and keyed for 'remove row benchmark' and non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
ERROR: Framework react-mlyn-v0.5.9-keyed is not correctly categorized
```
We could add it in the non-keyed section if that is what you want.

**Comment by vaukalak** [comment]
@krausest I've updated the branch to match the expected `keyed` framework behavior. Everything should work fine now. Thanks for your patience.

**Comment by krausest** [comment]
Thanks - that worked fine. [Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Pull request merged**
