### PR TITLE
update glimmer 2 from beta 10 to beta 16

### PR DESCRIPTION
**Pull request by lifeart**
updates

`"@glimmer/*": "^0.61.2"` to  `"@glimmer/*": "0.73.0"`

https://github.com/glimmerjs/glimmer-vm/compare/v0.61.1...v0.73.0

### CODE REVIEW

**Comment by krausest** [comment]
Sorry, I can't merge this PR since row selection doesn't work (no highlight on the row). Can you take a look at it please?

**Comment by krausest** [comment]
Sorry, row selections does not work for me. The danger class isn't applied to the tr when I click on a row.

**Comment by lifeart** [comment]
sorry for confusion, converting  it to draft until issue will be fixed

**Comment by lifeart** [comment]
@krausest looks like it's working right now (tested addition, removal, selection)

**Comment by krausest** [comment]
I'd rather delete glimmer-v0.14.0-alpha.13 now. Is that OK for you?

**Comment by lifeart** [comment]
@krausest ya, it’s fine, let me know if you need any help with it

**Pull request merged**
