### PR TITLE
Bump leptos to 0.5.0

### PR DESCRIPTION
**Pull request by birkskyum**
I noticed https://github.com/krausest/js-framework-benchmark/pull/1391 wasn't in sync with https://github.com/leptos-rs/leptos/blob/main/examples/js-framework-benchmark/src/lib.rs, so I made this pr.

It's not specific to this version, but I noticed `./bundled-dist/js-framework-benchmark-leptos.js` isn't minified when running `npm run build-prod-force` - @gbj , any idea why that is?

### CODE REVIEW

**Comment by krausest** [comment]
That's something new: Two updates for the same framework 👍 
@flosse @birkskyum Could you both please agree on which PR should be merged?

**Comment by flosse** [comment]
> That's something new: Two updates for the same framework 👍 @flosse @birkskyum 

:rofl: 

> Could you both please agree on which PR should be merged?

I wouldn't consider myself an expert of Leptos, which is why I give the lead to anyone who knows better :relaxed: 
Of course @gbj is the master here but he's probably also busy with more important topics :wink: 
So @birkskyum I think it's your turn now :smiley:

**Comment by gbj** [comment]
@birkskyum To keep it simpler I made a PR to your fork, not sure if you saw it.

**Comment by birkskyum** [comment]
Saw it only now

**Comment by birkskyum** [comment]
@krausest , this one is ready.

**Comment by krausest** [comment]
I'll post results here soon.

**Comment by krausest** [comment]
So here they are:
Screenshot 2023-10-09 at 10 24 27 PM

**Pull request merged**
