### PR TITLE
Update cample to v3.2.1-beta.0

### PR DESCRIPTION
**Pull request by antonmak1**
I solved the problem with the click without resorting to the methods described [here](https://github.com/krausest/js-framework-benchmark/issues/772). The main idea is a stack of real UI, where I store state that is not in contact with the main data. That is, this can be compared to how if we entered some data into the "input", and so this data is, as it were, reflected in this idea.

I don't know, maybe this is a trivial idea, but it sounds interesting to create a separate stack for each DOM element.

### CODE REVIEW

**Comment by krausest** [comment]
The [results](https://krausest.github.io/js-framework-benchmark/current.html) are updated (left updated keyed results, right old results). I guess we must take a look at the big picture in the next full run.
Screenshot 2024-07-05 at 07 37 07

**Comment by antonmak1** [comment]
@krausest Since the last release, I haven’t changed almost anything in other benchmarks, although the speed has dropped significantly. I don't know what the reason is. Well, this is a one-off launch, so that's ok. The main thing is that now select row shows quick results!

**Comment by antonmak1** [comment]
Everything is green - finally. Then only apply graphomaniac changes like changing classList to className, textContent to nodeValue, etc.

**Comment by antonmak1** [comment]
Anyway, thank you very much! I'm just glad that select row was fixed properly!

**Comment by antonmak1** [comment]
Everything is green. How beautiful!

**Pull request merged**
