### PR TITLE
Preact Signals Implementation

### PR DESCRIPTION
**Pull request by ryansolid**
Still figuring out if this is the best way of accomplishing this. Tried a few different versions but they have different tradeoffs. I also think I may have stumbled on a memory leak. Wouldn't mind a review.

@developit @marvinhagemeister

Thanks,

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Here are the results:
Bildschirmfoto 2022-09-12 um 21 15 17

**Comment by ryansolid** [comment]
I mean it's out there now. I marked it as a draft as I was hoping Jason would have time to address the memory leak first.

**Comment by krausest** [comment]
Sorry, didn't see that. Seems like I was too much in a hurry. Please let me know if I should remove it from the master branch.

**Comment by developit** [comment]
I'll try to get the fix PR'd today so we can update this benchmark. Would be nice to hold off on results and comparisons until that is done though, the current numbers are effectively meaningless.

**Comment by krausest** [comment]
Sorry, my fault. I'll delete the implementation from master and update the results and you'd post a new PR when it's ready.

**Comment by ryansolid** [comment]
The memory leak seems fixed in 1.0.4. Are we good @developit?

**Pull request merged**
