### PR TITLE
feat: add vue-vapor

### PR DESCRIPTION
**Pull request by sxzz**
Repo: https://github.com/vuejs/core-vapor

### CODE REVIEW

**Comment by antonmak1** [comment]
Implementation of a framework without a virtual DOM, respect! Promote the idea in web development!

**Comment by birkskyum** [comment]
Great work! I get these relative numbers for the keyed:

Screenshot 2024-02-11 at 23 55 10

**Comment by sxzz** [comment]
Here are the tests on my local machine. I'm investigating what reason caused it's slower than Vue 3.
image

**Comment by sxzz** [comment]
Here is the latest benchmark on the latest commit. In general, Vue and vue-vapor are currently quite similar, but Vapor still has significant room for optimization.

image

**Comment by krausest** [comment]
Thanks. Here's a screenshot (left new keyed results, right old keyed result).
Screenshot 2024-02-14 at 11 22 40

**Comment by sxzz** [comment]
Thanks for your work!

I would like to remind those who are concerned about Vue Vapor that the current performance of Vapor does not necessarily reflect the stability of the stable version.

**Pull request merged**
