### PR TITLE
Added wasm-bindgen

### PR DESCRIPTION
**Pull request by liamcurry**
This PR adds a keyed implementation for [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen), a Rust to WASM library that offers bindings for native JS similar to `stdweb`.

Most of the build code has been copied from the `stdweb` implementation. The results on my local machine are looking pretty good -- faster and smaller than `stdweb` at least.

### CODE REVIEW

**Comment by krausest** [comment]
Sounds interesting! 
But is seems like dist/main.js is missing. 
I tried to build it but I fail to do so (btw. it works for stdweb). This looks like the cause:
```
error[E0463]: can't find crate for `core`
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
```
How can I make it build?

**Comment by krausest** [comment]
I got just a little further and know too little rust to fix it:
```
   Replacing /Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/.cargo/bin/wasm-bindgen-test-runner
   Replacing /Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/.cargo/bin/wasm2es6js
   Replacing /Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/.cargo/bin/wasm-bindgen
/usr/local/bin/wasm-opt
error: failed to parse manifest at `/Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
Error: /Users/stefan/Source/Javascript/js-framework-benchmark/.cargo/bin/cargo +stable build -vv --release --target=wasm32-unknown-unknown: exit status=101
    at spawnSyncOrThrow (/Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/build.js:16:13)
    at /Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/build.js:136:5
    at Object.<anonymous> (/Users/stefan/Source/Javascript/js-framework-benchmark/frameworks/keyed/wasm-bindgen/build.js:187:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
Hash: 3a3a7ec2ec02001867dc
Version: webpack 4.28.4
Time: 295ms
Built at: 2019-01-17 21:28:18
 1 asset
Entrypoint main = main.js
[0] ./index.js 75 bytes {0} [built]
```

**Comment by liamcurry** [comment]
Looks like you might need to update Rust. Can you run this command and see what it outputs?

```sh
$ cargo +stable --version
cargo 1.32.0 (8610973aa 2019-01-02)
```

If it's less than `1.32.0` then run this command to update:

```sh
$ rustup update stable
```

The build script was mostly copied from the `stdweb` implementation, and it puts those binaries here:

- `js-framework-benchmark/.cargo/bin/cargo`
- `js-framework-benchmark/.cargo/bin/rustup`

So you will probably need to point to those binaries when you run the commands above.

**Comment by krausest** [comment]
It reports now:
cargo 1.32.0 (8610973aa 2019-01-02)
but the build still fails with the above message. 
Maybe you just commit dist/main.js?

**Comment by liamcurry** [comment]
Okay I committed all the `dist` files.

**Comment by krausest** [comment]
Thanks. It looks pretty good - here are the results for a first run. Very close to the fastest!

bildschirmfoto 2019-01-23 um 21 32 46

I'm a bit short of time currently, so I must ask your patience until I can merge your changes. I'd love to actually build the files (or if it really doesn't work out rename the dist folder, because its content are removed with the rebuild npm task)

**Comment by krausest** [comment]
I found out that "dist" was a silly idea since it's deleted when the rebuild-no-op task is invoked. I patched the path to "bundled-dist".

I still have no luck building it so I tried to setup a docker image, but I didn't get far (I couldn't get stdweb building there either most of the time with the cargo-features = ["edition"] error above. I changed projectDir in build.js to point to "/root"). 
Do you have a Dockerfile such that I could mount the directory and invoke npm run build-prod-force there?

**Pull request merged**
