### PR TITLE
Use Mimbl v0.10.3.

### PR DESCRIPTION
**Pull request by mmichlin66**

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Looks like a small performance regression.
Bildschirm­foto 2023-02-06 um 08 22 40

**Comment by mmichlin66** [comment]
Thank you, I’ll look into that (especially the #3 partial update, which was my forte 😊)

**Comment by mmichlin66** [comment]
Hi Stephan,

Lately, I started having problems building the results table. I can run the benchmark tests OK, but when I run “npm run results” I get the following error:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\dev\js-framework-benchmark\webdriver-ts-results\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

I am on a Windows 11 machine (but it started when I was on Windows 10). My node is v18.12.1. I also noticed that when I run “npm ci” in both webdriver-ts and webdriver-ts-results, I get many “vulnerabilities” and it suggests to run “npm audit fix” and even “npm audit fix –force", but running them didn’t help.

Do you have any advice on how to fix this?

Thank you,
Michael Michlin

**Comment by krausest** [comment]
I guess this is due to #1161 and `export NODE_OPTIONS=--openssl-legacy-provider` might be the solution.

**Comment by mmichlin66** [comment]
Thank you so much - this fixed it!

**Pull request merged**
