### PR TITLE
Update dojo2 to v0.2.0

### PR DESCRIPTION
**Pull request by agubler**
Update Dojo 2 dependency to 0.2.0

### CODE REVIEW

**Comment by krausest** [comment]
Thanks, but I'm afraid this version isn't keyed according to our definition here:
```
npm run nonKeyed -- --framework dojo2-v0.2.0-keyed
dojo2-v0.2.0-keyed is non-keyed for 'run benchmark' and non-keyed for 'remove row benchmark' non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
ERROR: Framework dojo2-v0.2.0-keyed is not correctly categorized in commons.ts
```
I prefer keyed frameworks (and maybe I'd even refuse to use a non-keyed framework). Any chance to get back a keyed version?
Until then I'll rename it to non-keyed.

**Comment by agubler** [comment]
@krausest Interesting so the definition of keyed isn't that there is an actual `key` being used but that the elements are "removed" and "created" as part of the tests?

**Comment by krausest** [comment]
Yes. I think that would be necessary for e.g. transitions to work correctly on key change.

**Comment by krausest** [comment]
See also https://github.com/krausest/js-framework-benchmark/issues/104#issuecomment-272099815

**Comment by agubler** [comment]
Yes that makes sense for when that's needed, have raised a keyed impl here https://github.com/krausest/js-framework-benchmark/pull/278

**Pull request merged**
