### PR TITLE
Refactor webdriver ts results

### PR DESCRIPTION
**Pull request by nakrovati**
- Make tables scrollable.
- Improve adaptability for mobile devices.
- Upgrade the `compilerOptions.target` version in tsconfig to ES2022
- Rename `DropdownContents` component to `SelectorContentContainer`.

And other minor updates

### CODE REVIEW

**Comment by krausest** [comment]
I just tried and it seems like deselecting frameworks doesn't work anymore (neither a single framework nor via the "None" button).

**Comment by nakrovati** [comment]
That's weird, I'll check it out.

**Comment by krausest** [comment]
I tweaked the css to avoid stretching the table if just a few frameworks are selected:
Screenshot 2023-10-02 at 9 14 22 PM

**Comment by nakrovati** [comment]
Good idea

**Pull request merged**
