### PR TITLE
ivi 4.0.0

### PR DESCRIPTION
**Pull request by leeoniya**
#1789

@krausest  no expected perf impact

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. I'm getting the following error in chrome's console:
```
bundle.js:1 Uncaught ReferenceError: Cannot access 'R' before initialization
    at bundle.js:1:9
```
Can you take a look at it?

**Comment by localvoid** [comment]
Sorry, it seems there is a bug with a deduplication optimization in a new typescript transformer plugin. I am gonna take a look at it.

**Comment by localvoid** [comment]
Published new `@ivi/ts-transformer` plugin that should fix the issue.

**Comment by krausest** [comment]
Thanks. Since I'm updating all (keyed) frameworks I'll post a full run the next days or weeks.

**Pull request merged**
