### PR TITLE
Update cample to 3.2.0-alpha.49

### PR DESCRIPTION
**Pull request by antonmak1**
I decided to look at the benchmark and saw that it was possible to redo the selection of rows. For some reason, I haven’t thought of such an implementation in a year or so :confused:

### CODE REVIEW

**Comment by antonmak1** [comment]
Wow, how stupid I am. I could not use the data that comes from the component, because in this case it is not necessary to store it. the line does not directly depend on them (but the label does). My code ended up going through the components 1000 times, and I kept wondering what was going on.

**Comment by pawelblaszczyk5** [comment]
I feel like the optimization added with this update fails under [this](https://github.com/krausest/js-framework-benchmark/issues/772) 😃

**Comment by antonmak1** [comment]
@pawelblaszczyk5 Yes, you may be right. I understood where the error in the slow operation of cample’s select row is in the code, but it’s better to fix it at the framework level.

**Comment by antonmak1** [comment]
@pawelblaszczyk5 Thank you! Yes, it looks like I was in a hurry and did it wrong.

**Pull request closed without merging**
