### PR TITLE
Update cample to 3.2.0-alpha.39

### PR DESCRIPTION
**Pull request by antonmak1**
Returned it, everything was as it was. I think select row will return to 3.5 - 3.8. I also updated the removal code, it will work faster there. In main.js, I removed the slice() method from "delete", because for good reason it, of course, should return different arrays, but in this particular case the data does not change quantitatively, so in this particular case the code still works fine without slice(). Somehow, I haven’t noticed this moment in the test for almost a year 😕

### CODE REVIEW

**Comment by antonmak1** [comment]
Hooray! I fixed the "select row" and finally found this stupid bug. It should definitely be really fast.

**Comment by krausest** [comment]
Here we go...
Screenshot 2024-04-06 at 20 09 56

**Comment by antonmak1** [comment]
Finally now "select row" works with adequate speed

**Comment by antonmak1** [comment]
"create rows" and "replace rows" seem to have broken down completely, although I didn’t change anything like that

**Comment by antonmak1** [comment]
In short, now I’ll return the code from version 29, that’s all.

**Pull request merged**
