### PR TITLE
Update Alpine, Solid, Svelte, Vue to latest

### PR DESCRIPTION
**Pull request by alpacone**

### CODE REVIEW

**Comment by krausest** [comment]
I'm afraid it'll take till next weekend until I can merge this PR. I'm currently transitioning to Fedora 35 and cleaning a few things up...

**Comment by ryansolid** [comment]
@alpacone  can I make a request. I was going to do it myself but you've already got an open PR. Rollup had a regression in terms of how does dead code elimination. I'd like to use < 2.53.x for rollup on the Solid builds. 2.52.3 is pretty good. At least until I can figure out another way of mitigating it.

**Comment by alpacone** [comment]
@ryansolid done. Also updated Solid to 1.2.1.

**Comment by krausest** [comment]
Thanks - results are updated. Looks like preact got a bit faster for select rows.

**Pull request merged**
