### PR TITLE
Updated Voby to v0.43

### PR DESCRIPTION
**Pull request by fabiospampinato**
Lots of litte-ish internal changes, so here's an update.

### CODE REVIEW

**Comment by leeoniya** [comment]
or even 0.43.1 ;)

https://github.com/vobyjs/voby/commit/ce1e8bb15a4285a4a44ec8f089af327895366684

**Comment by krausest** [comment]
Nice!
Bildschirmfoto 2022-10-22 um 21 48 46

**Comment by fabiospampinato** [comment]
It looks like the current table didn't get updated this time around.

**Comment by krausest** [comment]
Sorry! It's fixed now.

**Pull request merged**
