### PR TITLE
Added Eventiveness Web framework

### PR DESCRIPTION
**Pull request by mksunny1**
I have created a powerful new web framework comprising 7 independent libraries and directly benefited from using these benchmarks to test and improve my abstractions. The performance is very good. And thanks for doing these benchmarks.

### CODE REVIEW

**Comment by krausest** [comment]
Thanks - I hope to publish results for the PR tomorrow.

**Comment by krausest** [comment]
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated. Deleight performs nicely! 

I'll fix the version naming.

**Comment by mksunny1** [comment]
Wow, special thanks! This has been a fantastic learning experience. Your VanillaJS implementation changed some of my assumptions about JavaScript performance. JS is faster than I thought. 

Deleight is not a framework. I created some cost-less (or nearly cost-less) high-level primitives to simplify and accelerate front-end programming. The features must not already exist directly in JavaScript and must provide clear benefits. The performance and how the libraries are used should be up to the programmer. JavaScript is my favourite language and I would like a few more people to see and use it like I do.

**Comment by mksunny1** [comment]
For VanillaJS-3, I am adding async and defer attributes explicitly in the script tag to force asynchronous loading. That improves the time to first paint.

**Pull request merged**
