### PR TITLE
Update cample to 3.2.0-alpha.45

### PR DESCRIPTION
**Pull request by antonmak1**
Fixed select row. It will be better.

### CODE REVIEW

**Comment by krausest** [comment]
I'm sorry, all PRs are currently blocked by https://github.com/krausest/js-framework-benchmark/issues/1655

**Comment by antonmak1** [comment]
@krausest The main thing is to solve the problem with unclear test results.

**Comment by antonmak1** [comment]
It can all wait, whatever

**Comment by antonmak1** [comment]
Hooray! Finally fixed the select row to a more or less normal state

**Comment by krausest** [comment]
Thanks - I hope to publish results for the PR tomorrow.

**Comment by antonmak1** [comment]
I didn't do anything anymore. In version 124 I just saw that the result was normal, so I wrote it. It just took me quite a while to fix it. Well, I was just happy and wrote about it in pr :-)

**Comment by krausest** [comment]
Yeah, I stumped upon that the version number looked so similar :)

**Pull request merged**
