### PR TITLE
update Vue to 2.1.3 and use build-time template compilation

### PR DESCRIPTION
**Pull request by yyx990803**
In-browser compilation results in less-than-ideal render functions. In production `vue-loader` can apply some build-time optimizations.

### CODE REVIEW

**Comment by anthonyettinger** [comment]
curious how vue 2.x performs now.

**Comment by krausest** [comment]
npm run build-prod results in an error on my machine. Any idea how to fix it?
[Here's the npm log](https://github.com/krausest/js-framework-benchmark/files/624729/npm_log.txt)

**Comment by yyx990803** [comment]
Somehow `-c webpack.config.js` in the script is making Webpack bundle itself instead of the app... this might be a bug in webpack's CLI. Fixed.

**Comment by krausest** [comment]
Building works now, but I get an error when I try to remove a row
```main.js:1 Uncaught TypeError: Cannot add/remove sealed array elements(…)```
It works when the sync method doesn't freeze the rows:
```
        sync() {
            this.rows = store.data;
            this.selected = Object.freeze(store.selected);
        }
```
Is it ok to commit it that way?

**Comment by yyx990803** [comment]
Oops, fixed :)

**Comment by krausest** [comment]
Thanks! It's merged now. According to #89 I'll change the requirements which means I'll update vue to use a key in v-for. Feel free to comment regarding the tracking/non-tracking issue.

**Pull request merged**
