### PR TITLE
feat(preact-hook, preact-signals): use memo to render row component

### PR DESCRIPTION
**Pull request by hi-ogawa**
- related to https://github.com/krausest/js-framework-benchmark/pull/1425

I noticed that preact hooks/signals is recently introduced in https://github.com/krausest/js-framework-benchmark/pull/1425 and it seems it has a huge gap both from preact-class and react-hooks for "select 1k" bench.
If I'm not mistaken, the lack of memo for row rendering has a significant effect for "select 1k" bench since "memo"-ed version can skip most of reconcilation work for the rows with the same "selected" state, which is essentially the case for `998 = 1000 - 2` rows.
(preact-classes doesn't have "memo", but I think `shouldComponentUpdate` achieves mostly the same thing as `memo`).

(EDIT: now I put the generated table below) ~As I recently discovered this repo, I haven't managed to generate complete html result table for the comparison, but I observed some effect on timing when checking devtools directly.~

<details><summary>reveal devtools screenshot</summary>

- before

스크린샷 2023-10-28 11-42-59

- after

스크린샷 2023-10-28 11-47-31

</details>

~Such primitive measurement might not be reliable and maybe I'm missing something, but I was wondering what others think about the effect of "memo" in general.~

@birkskyum Hi. I'm curious whether you've experimented with "memo"-ed version while you were working on https://github.com/krausest/js-framework-benchmark/pull/1425. I'd appreciate any feedback. Thanks!

---

~Sorry about the lack of bench table screenshot. I'll follow README.md and will provide a new comparison preact-classes and preact-hooks later.~

On my PC, I got a following result. So, it looks like the use of `memo` might have negative impact on "swap rows", which was not observed in https://github.com/krausest/js-framework-benchmark/pull/1425.

(EDIT: added also react-hooks)

image

### CODE REVIEW

**Comment by birkskyum** [comment]
Hi @hi-ogawa ,

Thank you for investigating this!

I didn't look into the memo for the initial implementation, so there might be something there.

**Comment by hi-ogawa** [comment]
I didn't expect `memo` would affect "swap rows" negatively, so I have to investigate a little further.
In the mean time, I'll put this PR as a draft, but I'd appreciate any comment if others have any insight on this.
Also, my PC is pretty low spec, so if anyone with more decent setup is interested in running this change locally for better comparison, that would be great as well.
Thanks!

**Comment by birkskyum** [comment]
I tried adding the memo, but the results were not great

Screenshot 2023-10-30 at 01 32 25

**Comment by krausest** [comment]
How do we continue from here? Does it help coming up with a decision if I run the PR (I suppose it will be pretty similar to @birkskyum)?

**Comment by birkskyum** [comment]
I tried to be quite thorough, to make sure there weren't "bad runs" playing tricks, but feel free to double check. I don't think it's particularly interesting to introduce the memo versions in the benchmark - but it's still noteworthy that there _is_ an improvement in the **select row**. As I see it, the best-case scenario for this PR is if it can provide a useful hint to a framework author on how to improve that specific metric without introducing those regressions.

**Comment by hi-ogawa** [comment]
Thanks for pinging and sorry for not taking actions here.

I initially thought `memo` would win all cases, but that doesn't seem to be the case.
Understanding preact's optimization which makes this difference is probably beyond what I'm capable of right now, so unless preact team is interested in investigating this specific perf characteristics of `memo` (I think they probably are not so, considering comment such as https://github.com/krausest/js-framework-benchmark/pull/1425#issuecomment-1764912692), I don't think I can continue further.

I'm still interested in preact's diffing and optimization against this specific benchmark repo, so if I find something I can say concretely, then I might come back with some result, but for now let me close this PR.
Thanks for taking your time on considering this!

**Pull request closed without merging**
