### PR TITLE
update react-easy-state to v3 and add non-keyed version

### PR DESCRIPTION
**Pull request by solkimicreb**
Update [React Easy State](https://github.com/solkimicreb/react-easy-state) to v3.0.0 and add non-keyed version. It performs similarly to Redux on my machine.

### CODE REVIEW

**Comment by solkimicreb** [comment]
I will check the issue tomorrow morning (:

**Comment by solkimicreb** [comment]
webdriver-ts `npm run build-prod` fails for me with this:

```bash
Executing npm run build-prod in webdriver-ts

> webdriver-ts@1.0.0 build-prod /home/circleci/project/webdriver-ts
> tsc

src/webdriverAccess.ts(93,9): error TS2345: Argument of type '(driver: WebDriver) => Promise<boolean | void>' is not assignable to parameter of type '(driver: WebDriver) => Promise<boolean>'.
  Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
    Type 'boolean | void' is not assignable to type 'boolean'.
      Type 'void' is not assignable to type 'boolean'.
src/webdriverAccess.ts(102,9): error TS2345: Argument of type '(driver: WebDriver) => Promise<boolean | void>' is not assignable to parameter of type '(driver: WebDriver) => Promise<boolean>'.
  Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
src/webdriverAccess.ts(111,9): error TS2345: Argument of type '(driver: WebDriver) => Promise<boolean | void>' is not assignable to parameter of type '(driver: WebDriver) => Promise<boolean>'.
  Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
src/webdriverAccess.ts(130,9): error TS2345: Argument of type '(driver: WebDriver) => Promise<boolean | void>' is not assignable to parameter of type '(driver: WebDriver) => Promise<boolean>'.
  Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
src/webdriverAccess.ts(138,9): error TS2345: Argument of type '(driver: WebDriver) => Promise<boolean | void>' is not assignable to parameter of type '(driver: WebDriver) => Promise<boolean>'.
  Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
src/webdriverAccess.ts(145,5): error TS2322: Type 'Promise<void | T>' is not assignable to type 'Promise<T>'.
  Type 'void | T' is not assignable to type 'T'.
    Type 'void' is not assignable to type 'T'.
```

Could you help me out with this?

**Comment by krausest** [comment]
I‘m on holiday this and next week and I‘ll merge it when I‘m back and look into the webdriver-ts compiler error. Pretty sure it‘s just some dependency that didn‘t use a fixed version number and not caused by your pull request.

**Comment by solkimicreb** [comment]
Yes, I just found it out too. I see you fixed them. Thanks and have a nice holiday (:

**Comment by krausest** [comment]
Very nice. Results are [here](https://rawgit.com/krausest/js-framework-benchmark/b6228535b2b54de7bfe02483411e8aacaccf2a1c/webdriver-ts-results/table.html).
In practice as fast as the pure react version.

Would you mind if I removed the non-keyed in a future release? I think I doesn't add much value to the comparison of keyed pure react vs. keyed react with a state lib and I'd like to avoid maintaining non-keyed implementations for all other react state libs.

**Comment by solkimicreb** [comment]
Thanks 🙂 Sure, I am fine with removing the non-keyed version (it was a 1 min change from my side). Should I send a PR?

**Pull request merged**
