### PR TITLE
Updated to Inferno@beta9

### PR DESCRIPTION
**Pull request by trueadm**

### CODE REVIEW

**Comment by leeoniya** [comment]
this also updates angular-v2.0.0

:/

**Comment by trueadm** [comment]
Yeah, I haven't had time to change the PR. I'll probably have to close this PR and re-address next month – I'm off tomorrow so won't be around to do these PRs anymore :(.

**Comment by krausest** [comment]
I'll merge the neccessary changes manually and then close the PR if that's okay for you.

**Comment by trueadm** [comment]
@krausest awesome, thank you!

**Comment by krausest** [comment]
I tried my best, but failed. Webpack gives me the following error apparently due to the noNormalize attributes. 
```
ERROR in ./src/controller.jsx
Module build failed: TypeError: /Users/stefan/Source/Javascript/js-framework-benchmark/inferno-v1.0.0-beta9/src/controller.jsx: Property value expected type of boolean but got string
```

**Comment by trueadm** [comment]
Can you try with Babel-plugin-inferno@beta10

**Comment by krausest** [comment]
babel-plugin-inferno@1.2.0-beta11 did the trick..

**Comment by trueadm** [comment]
Awesome :) thank you for looking into it

**Pull request merged**
