### PR TITLE
Adding neow to the family

### PR DESCRIPTION
**Pull request by eavichay**

### CODE REVIEW

**Comment by krausest** [comment]
Just FYI: I'm a bit short of time so I plan to merge the PR this weekend

**Comment by eavichay** [comment]
Neo has NO BUILD steps, it's pure javascript.
The build breaks on WASM project.

**Comment by krausest** [comment]
Hello neow (though it's one of the black :sheep::sheep:  in the family being non-keyed :smile: )
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by eavichay** [comment]
👍 Thank!

**Pull request merged**
