### PR TITLE
Update Mikado to v0.6.34

### PR DESCRIPTION
**Pull request by ts-thomas**
A lot of new performance optimizations was introduced in Mikado since 0.1.2. Most of them are runtime optimizations which are not covered by this benchmark tests :(
Still there are slightly improvements noticeable, the build filesize is lower, the implementation shrinks to an absolute minimum, the memory consumption was improved, the process flow was also improved. Also some changes to the template syntax accordingly to the versions >= 0.4.0.

### CODE REVIEW

**Comment by krausest** [comment]
@ts-thomas Sorry the build fails with the following error:
```
> js-framework-benchmark-mikado@ compile /build/frameworks/keyed/mikado
> mikado-compile src/template/app.html && mikado-compile src/template/item.html && echo Compile Complete. && exit 0

Compile Complete.
Start build .....

DEBUG: false
USE_POLYFILL: false
SUPPORT_CACHE: false
SUPPORT_EVENTS: true
SUPPORT_STORAGE: true
SUPPORT_HELPERS: swap
SUPPORT_ASYNC: false
SUPPORT_TRANSPORT: false
SUPPORT_TEMPLATE_EXTENSION: false
SUPPORT_REACTIVE: false
SUPPORT_CACHE_HELPERS: false
SUPPORT_POOLS: false
SUPPORT_COMPILE: false
RELEASE: custom
node_modules/mikado/src/event.js:3: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_EVENTS is undeclared
if(SUPPORT_EVENTS){
   ^^^^^^^^^^^^^^

node_modules/mikado/src/event.js:78: ERROR - [JSC_UNDEFINED_VARIABLE] variable DEBUG is undeclared
        else if(DEBUG){
                ^^^^^

node_modules/mikado/src/helper.js:3: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_HELPERS is undeclared
if(SUPPORT_HELPERS){
   ^^^^^^^^^^^^^^^

node_modules/mikado/src/helper.js:71: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_STORAGE is undeclared
                if(SUPPORT_STORAGE && !multi_update && this.reuse && (this.store || this.loose)){
                   ^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:70: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_POOLS is undeclared
if(SUPPORT_POOLS){
   ^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:75: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_CACHE is undeclared
if(SUPPORT_CACHE){
   ^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:204: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_CACHE_HELPERS is undeclared
                if(SUPPORT_CACHE_HELPERS){
                   ^^^^^^^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:466: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_TEMPLATE_EXTENSION is undeclared
        if(SUPPORT_TEMPLATE_EXTENSION) this["include"] = null;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:2246: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_TRANSPORT is undeclared
if(SUPPORT_TRANSPORT){
   ^^^^^^^^^^^^^^^^^

node_modules/mikado/src/polyfill.js:1: ERROR - [JSC_UNDEFINED_VARIABLE] variable USE_POLYFILL is undeclared
if(USE_POLYFILL){
   ^^^^^^^^^^^^

node_modules/mikado/src/polyfill.js:42: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_ASYNC is undeclared
    if(SUPPORT_ASYNC){
       ^^^^^^^^^^^^^

node_modules/mikado/src/proxy.js:72: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_REACTIVE is undeclared
if(SUPPORT_REACTIVE){
   ^^^^^^^^^^^^^^^^

12 error(s), 0 warning(s)
{ Error: Command failed: java -jar node_modules/google-closure-compiler-java/compiler.jar --compilation_level=ADVANCED_OPTIMIZATIONS --use_types_for_optimization=true --jscomp_warning=newCheckTypes --jscomp_error=newCheckTypesExtraChecks --generate_exports=true --export_local_property_definitions=true --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --process_closure_primitives=true --summary_detail_level=3 --warning_level=VERBOSE --emit_use_strict=true --output_manifest=log/manifest.log --output_module_dependencies=log/module_dependencies.log --property_renaming_report=log/property_renaming.log --create_source_map=log/source_map.log --variable_renaming_report=log/variable_renaming.log --strict_mode_input=true --assume_function_wrapper=true --transform_amd_modules=true --process_common_js_modules=true --module_resolution=BROWSER --entry_point=./src/main.js --dependency_mode=PRUNE_LEGACY --rewrite_polyfills=false --isolation_mode=IIFE --js='src/*.js' --js='src/template/*.es6.js' --js='node_modules/mikado/src/*.js' --js='!node_modules/mikado/src/*config.js' --define='RELEASE=custom' --define='DEBUG=false' --define='USE_POLYFILL=false' --define='SUPPORT_CACHE=false' --define='SUPPORT_EVENTS=true' --define='SUPPORT_STORAGE=true' --define='SUPPORT_HELPERS=swap' --define='SUPPORT_ASYNC=false' --define='SUPPORT_TRANSPORT=false' --define='SUPPORT_TEMPLATE_EXTENSION=false' --define='SUPPORT_REACTIVE=false' --define='SUPPORT_CACHE_HELPERS=false' --define='SUPPORT_POOLS=false' --define='SUPPORT_COMPILE=false' --js_output_file='dist/main.js' && exit 0
node_modules/mikado/src/event.js:3: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_EVENTS is undeclared
if(SUPPORT_EVENTS){
   ^^^^^^^^^^^^^^

node_modules/mikado/src/event.js:78: ERROR - [JSC_UNDEFINED_VARIABLE] variable DEBUG is undeclared
        else if(DEBUG){
                ^^^^^

node_modules/mikado/src/helper.js:3: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_HELPERS is undeclared
if(SUPPORT_HELPERS){
   ^^^^^^^^^^^^^^^

node_modules/mikado/src/helper.js:71: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_STORAGE is undeclared
                if(SUPPORT_STORAGE && !multi_update && this.reuse && (this.store || this.loose)){
                   ^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:70: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_POOLS is undeclared
if(SUPPORT_POOLS){
   ^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:75: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_CACHE is undeclared
if(SUPPORT_CACHE){
   ^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:204: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_CACHE_HELPERS is undeclared
                if(SUPPORT_CACHE_HELPERS){
                   ^^^^^^^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:466: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_TEMPLATE_EXTENSION is undeclared
        if(SUPPORT_TEMPLATE_EXTENSION) this["include"] = null;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

node_modules/mikado/src/mikado.js:2246: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_TRANSPORT is undeclared
if(SUPPORT_TRANSPORT){
   ^^^^^^^^^^^^^^^^^

node_modules/mikado/src/polyfill.js:1: ERROR - [JSC_UNDEFINED_VARIABLE] variable USE_POLYFILL is undeclared
if(USE_POLYFILL){
   ^^^^^^^^^^^^

node_modules/mikado/src/polyfill.js:42: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_ASYNC is undeclared
    if(SUPPORT_ASYNC){
       ^^^^^^^^^^^^^

node_modules/mikado/src/proxy.js:72: ERROR - [JSC_UNDEFINED_VARIABLE] variable SUPPORT_REACTIVE is undeclared
if(SUPPORT_REACTIVE){
   ^^^^^^^^^^^^^^^^

12 error(s), 0 warning(s)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 12,
  signal: null,
  cmd:
   'java -jar node_modules/google-closure-compiler-java/compiler.jar --compilation_level=ADVANCED_OPTIMIZATIONS --use_types_for_optimization=true --jscomp_warning=newCheckTypes --jscomp_error=newCheckTypesExtraChecks --generate_exports=true --export_local_property_definitions=true --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --process_closure_primitives=true --summary_detail_level=3 --warning_level=VERBOSE --emit_use_strict=true --output_manifest=log/manifest.log --output_module_dependencies=log/module_dependencies.log --property_renaming_report=log/property_renaming.log --create_source_map=log/source_map.log --variable_renaming_report=log/variable_renaming.log --strict_mode_input=true --assume_function_wrapper=true --transform_amd_modules=true --process_common_js_modules=true --module_resolution=BROWSER --entry_point=./src/main.js --dependency_mode=PRUNE_LEGACY --rewrite_polyfills=false --isolation_mode=IIFE --js=\'src/*.js\' --js=\'src/template/*.es6.js\' --js=\'node_modules/mikado/src/*.js\' --js=\'!node_modules/mikado/src/*config.js\' --define=\'RELEASE=custom\' --define=\'DEBUG=false\' --define=\'USE_POLYFILL=false\' --define=\'SUPPORT_CACHE=false\' --define=\'SUPPORT_EVENTS=true\' --define=\'SUPPORT_STORAGE=true\' --define=\'SUPPORT_HELPERS=swap\' --define=\'SUPPORT_ASYNC=false\' --define=\'SUPPORT_TRANSPORT=false\' --define=\'SUPPORT_TEMPLATE_EXTENSION=false\' --define=\'SUPPORT_REACTIVE=false\' --define=\'SUPPORT_CACHE_HELPERS=false\' --define=\'SUPPORT_POOLS=false\' --define=\'SUPPORT_COMPILE=false\' --js_output_file=\'dist/main.js\' && exit 0' }
```

**Comment by ts-thomas** [comment]
Sorry my fault. The config file was missing, I cleaned up too much :)

**Comment by ts-thomas** [comment]
Something was wrong, I will re-open when fixed.

**Comment by ts-thomas** [comment]
Fixed.

**Pull request closed without merging**
