### PR TITLE
Updated Voby to v0.37

### PR DESCRIPTION
**Pull request by fabiospampinato**
It's been a few released, so here's an update.

For whatever reason the script that rebuilds the table is failing on me, I get this in the console:

```
ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(24,106)
      TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(27,67)
      TS2345: Argument of type '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }' is not assignable to parameter of type 'Framework'.
  Types of property 'name' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(72,3)
      TS2322: Type '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }[]' is not assignable to type 'Framework[]'.
  Type '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }' is not assignable to type 'Framework'.

ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(74,5)
      TS2418: Type of computed property's value is '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }[]', which is not assignable to type 'Framework[]'.

ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(75,5)
      TS2418: Type of computed property's value is '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }[]', which is not assignable to type 'Framework[]'.

ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(116,52)
      TS2345: Argument of type '{ name: string | undefined; dir: string; displayname: string; issues: number[]; type: FrameworkType; }' is not assignable to parameter of type 'Framework'.
Child HtmlWebpackCompiler:
                          Asset      Size  Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  4.18 KiB       0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 601 bytes {0} [built]
```

The `results.json` file is generated properly though.

### CODE REVIEW

**Comment by krausest** [comment]
Hi @fabiospampinato and thanks, I'll merge this weekend.
Regarding the error I'd say that there's some invalid entry in results.ts
If you want you can raise an issue and upload the results.ts file such that I can take a look. Seems like one of the frameworks doesn't have a name or so. Is there maybe an invalid directory in the keyed or non-keyed framework directories?

**Comment by fabiospampinato** [comment]
This is the `results.ts` I have:

```ts
import {RawResult} from './Common';

export const results: RawResult[]=[
{"f":"solid-v1.4.4-keyed","b":"01_run1k","v":[36.004,36.607,36.794,36.854,36.88,37.241,38.865,39.062,39.334,39.631]},
{"f":"solid-v1.4.4-keyed","b":"02_replace1k","v":[38.534,38.654,38.749,39.602,39.726,39.766,40.434,40.509,40.56,40.736]},
{"f":"solid-v1.4.4-keyed","b":"03_update10th1k_x16","v":[10.39,11.339,11.524,11.689,11.742,11.797,12.04,12.272,12.359,13.801]},
{"f":"solid-v1.4.4-keyed","b":"04_select1k","v":[2.732,3.215,3.267,3.663,3.673,4.033,4.101,4.134,4.291,4.728]},
{"f":"solid-v1.4.4-keyed","b":"05_swap1k","v":[12.183,12.444,12.791,12.843,13.346,13.389,13.396,13.406,13.513,13.552]},
{"f":"solid-v1.4.4-keyed","b":"06_remove-one-1k","v":[9.594,9.729,9.733,9.789,10.005,10.034,10.15,10.641,10.711,10.716]},
{"f":"solid-v1.4.4-keyed","b":"07_create10k","v":[427.469,429.667,434.004,435.25,435.597,436.07,438.283,439.266,440.145,441.217]},
{"f":"solid-v1.4.4-keyed","b":"08_create1k-after1k_x2","v":[40.147,41.013,41.108,41.327,41.378,41.449,43.388,44.45,45.044,46.337]},
{"f":"solid-v1.4.4-keyed","b":"09_clear1k_x8","v":[7.061,7.188,7.318,7.342,7.389,7.411,7.423,7.444,7.496,7.918]},
{"f":"solid-v1.4.4-keyed","b":"21_ready-memory","v":[1.0588874816894531]},
{"f":"solid-v1.4.4-keyed","b":"22_run-memory","v":[2.0819358825683594]},
{"f":"solid-v1.4.4-keyed","b":"23_update5-memory","v":[2.113025665283203]},
{"f":"solid-v1.4.4-keyed","b":"25_run-clear-memory","v":[1.1918563842773438]},
{"f":"solid-v1.4.4-keyed","b":"31_startup-ci","v":[1893.8649999999998,1895.525,1889.9599999999998,1899.95]},
{"f":"solid-v1.4.4-keyed","b":"32_startup-bt","v":[0,0,0,0]},
{"f":"solid-v1.4.4-keyed","b":"34_startup-totalbytes","v":[149.83203125,149.83203125,149.83203125,149.83203125]},
{"f":"vanillajs-keyed","b":"01_run1k","v":[33.567,33.626,34.45,34.565,34.616,34.919,34.96,35.837,36.459,37.291]},
{"f":"vanillajs-keyed","b":"02_replace1k","v":[36.224,36.651,36.909,37.27,37.49,37.578,37.615,37.802,37.86,38.853]},
{"f":"vanillajs-keyed","b":"03_update10th1k_x16","v":[10.666,10.99,11.128,11.136,11.406,11.684,11.816,11.879,12.023,12.293]},
{"f":"vanillajs-keyed","b":"04_select1k","v":[2.354,2.362,2.509,2.655,2.756,2.776,2.82,2.921,2.934,2.959]},
{"f":"vanillajs-keyed","b":"05_swap1k","v":[12.271,12.334,12.354,12.513,12.586,12.851,12.96,13.15,13.197,13.298]},
{"f":"vanillajs-keyed","b":"06_remove-one-1k","v":[9.118,9.132,9.496,9.531,9.534,9.593,9.637,9.731,9.805,9.828]},
{"f":"vanillajs-keyed","b":"07_create10k","v":[360.63,362.615,367.342,367.46,372.465,397.403,424.442,425.614,451.922,458.503]},
{"f":"vanillajs-keyed","b":"08_create1k-after1k_x2","v":[38.531,38.815,38.852,38.868,38.985,39.135,39.789,40.35,41.12,42.581]},
{"f":"vanillajs-keyed","b":"09_clear1k_x8","v":[6.528,6.554,6.599,6.603,6.619,6.693,6.712,6.765,6.795,6.943]},
{"f":"vanillajs-keyed","b":"21_ready-memory","v":[1.0346717834472656]},
{"f":"vanillajs-keyed","b":"22_run-memory","v":[1.3009719848632812]},
{"f":"vanillajs-keyed","b":"23_update5-memory","v":[1.3109474182128906]},
{"f":"vanillajs-keyed","b":"25_run-clear-memory","v":[1.0841903686523438]},
{"f":"vanillajs-keyed","b":"31_startup-ci","v":[1876.5700000000002,1877.3249999999998,1890.415,1885.4399999999998]},
{"f":"vanillajs-keyed","b":"32_startup-bt","v":[0.04000000000000001,0,0,0]},
{"f":"vanillajs-keyed","b":"34_startup-totalbytes","v":[150.3916015625,150.3916015625,150.3916015625,150.3916015625]},
{"f":"voby-v0.37.0-keyed","b":"01_run1k","v":[38.1,38.341,38.438,38.541,38.624,39.268,39.466,42.272,42.968,45.17]},
{"f":"voby-v0.37.0-keyed","b":"02_replace1k","v":[38.741,39.334,39.399,39.663,39.934,39.941,40.006,40.025,40.045,40.275]},
{"f":"voby-v0.37.0-keyed","b":"03_update10th1k_x16","v":[10.36,10.998,11.093,11.361,11.423,11.628,11.707,11.768,11.951,12.025]},
{"f":"voby-v0.37.0-keyed","b":"04_select1k","v":[2.603,2.733,2.752,2.797,2.808,3.023,3.026,3.049,3.168,3.32]},
{"f":"voby-v0.37.0-keyed","b":"05_swap1k","v":[12.454,12.709,12.804,12.865,13.085,13.504,13.533,13.546,13.84,13.851]},
{"f":"voby-v0.37.0-keyed","b":"06_remove-one-1k","v":[9.619,9.849,9.913,9.941,9.968,10.071,10.082,10.182,10.224,10.348]},
{"f":"voby-v0.37.0-keyed","b":"07_create10k","v":[444.839,445.191,446.245,446.719,450.293,450.421,452.338,457.366,458.161,460.24]},
{"f":"voby-v0.37.0-keyed","b":"08_create1k-after1k_x2","v":[43.134,43.199,43.339,43.357,43.626,43.704,43.742,44.983,46.607,46.706]},
{"f":"voby-v0.37.0-keyed","b":"09_clear1k_x8","v":[7.865,7.888,7.95,8.003,8.003,8.012,8.051,8.139,8.242,8.456]},
{"f":"voby-v0.37.0-keyed","b":"21_ready-memory","v":[1.18475341796875]},
{"f":"voby-v0.37.0-keyed","b":"22_run-memory","v":[2.0540924072265625]},
{"f":"voby-v0.37.0-keyed","b":"23_update5-memory","v":[2.0649795532226562]},
{"f":"voby-v0.37.0-keyed","b":"25_run-clear-memory","v":[1.6108169555664062]},
{"f":"voby-v0.37.0-keyed","b":"31_startup-ci","v":[2026.5300000000002,1955.2949999999998,2026.395,2027.545]},
{"f":"voby-v0.37.0-keyed","b":"32_startup-bt","v":[0,0.04800000000000001,0,0]},
{"f":"voby-v0.37.0-keyed","b":"34_startup-totalbytes","v":[169.0556640625,169.0556640625,169.0556640625,169.0556640625]},];
export const frameworks = [{"dir":"keyed/.DS_Store","keyed":true},{"name":"1more-v0.1.18-keyed","dir":"keyed/1more","keyed":true},{"name":"alpine-v3.10.2-keyed","dir":"keyed/alpine","keyed":true},{"name":"angular-v13.0.0-keyed","dir":"keyed/angular","keyed":true},{"name":"angular-nozone-v13.0.0-keyed","dir":"keyed/angular-nozone","keyed":true},{"name":"angularjs-v1.8.2-keyed","dir":"keyed/angularjs","keyed":true},{"name":"apprun-v2.28.3-keyed","dir":"keyed/apprun","keyed":true,"issues":[801]},{"name":"art-v0.1.7-keyed","dir":"keyed/art","keyed":true},{"name":"bdc-v1.0.0-keyed","dir":"keyed/bdc","keyed":true},{"name":"blazor-wasm-v6.0.1-keyed","dir":"keyed/blazor-wasm","keyed":true},{"name":"blazor-wasm-aot-v6.0.1-keyed","dir":"keyed/blazor-wasm-aot","keyed":true},{"name":"blockdom-v0.9.26-keyed","dir":"keyed/blockdom","keyed":true},{"name":"bobril-v8.11.2-keyed","dir":"keyed/bobril","keyed":true},{"name":"callbag-jsx-v0.0.29-keyed","dir":"keyed/callbag-jsx","keyed":true},{"name":"callbag-jsx-list-v0.0.29-keyed","dir":"keyed/callbag-jsx-list","keyed":true},{"name":"choo-v6.13.0-keyed","dir":"keyed/choo","keyed":true},{"dir":"keyed/compostate-jsx","keyed":true},{"name":"crank-v0.4.1-keyed","dir":"keyed/crank","keyed":true},{"name":"dioxus-v0.2.4-keyed","dir":"keyed/dioxus","keyed":true},{"name":"dojo-v8.0.0-keyed","dir":"keyed/dojo","keyed":true},{"name":"domdiff-v2.2.2-keyed","dir":"keyed/domdiff","keyed":true,"issues":[772]},{"name":"dominator-v0.5.0-keyed","dir":"keyed/dominator","keyed":true},{"name":"domvm-v3.4.12-keyed","dir":"keyed/domvm","keyed":true},{"name":"doohtml-keyed","dir":"keyed/doohtml","keyed":true,"issues":[772]},{"name":"doz-v3.4.1-keyed","dir":"keyed/doz","keyed":true,"issues":[800]},{"name":"dyo-v1.0.0-keyed","dir":"keyed/dyo","keyed":true},{"name":"ef-js-v0.13.12-keyed","dir":"keyed/ef-js","keyed":true},{"name":"elm-v0.19.1-3-keyed","dir":"keyed/elm","keyed":true},{"name":"ember-v4.2.0-keyed","dir":"keyed/ember","keyed":true},{"name":"endorphin-v0.5.2-keyed","dir":"keyed/endorphin","keyed":true},{"name":"etch-v0.14.1-keyed","dir":"keyed/etch","keyed":true,"issues":[634]},{"name":"fntags-v0.3.3-keyed","dir":"keyed/fntags","keyed":true},{"name":"forgo-v2.2.3-keyed","dir":"keyed/forgo","keyed":true},{"name":"fre-v2.5.5-keyed","dir":"keyed/fre","keyed":true},{"name":"fullweb-helpers-v0.1.0-keyed","dir":"keyed/fullweb-helpers","keyed":true,"issues":[772]},{"name":"fullweb-template-v0.1.0-keyed","dir":"keyed/fullweb-template","keyed":true,"issues":[772]},{"name":"ganic-v2.1.2-keyed","dir":"keyed/ganic","keyed":true},{"name":"glimmer-v0.14.0-alpha.13-keyed","dir":"keyed/glimmer","keyed":true,"issues":[800]},{"name":"glimmer-2-v2.0.0-beta.20-keyed","dir":"keyed/glimmer-2","keyed":true},{"name":"helix-v0.0.10-keyed","dir":"keyed/helix","keyed":true},{"name":"heresy-v0.26.1-keyed","dir":"keyed/heresy","keyed":true,"issues":[801]},{"name":"hullo-v0.8.2-keyed","dir":"keyed/hullo","keyed":true},{"name":"hydro-js-v1.5.13-keyed","dir":"keyed/hydro-js","keyed":true},{"name":"hyperapp-v2.0.22-keyed","dir":"keyed/hyperapp","keyed":true},{"name":"hyperhtml-v2.32.1-keyed","dir":"keyed/hyperhtml","keyed":true,"issues":[801]},{"name":"imba-v1.5.2-keyed","dir":"keyed/imba","keyed":true},{"name":"inferno-v7.4.8-keyed","dir":"keyed/inferno","keyed":true},{"name":"isotope-v0.2.0-keyed","dir":"keyed/isotope","keyed":true},{"name":"ivi-v0.27.1-keyed","dir":"keyed/ivi","keyed":true},{"name":"jotai-v17.0.1 + 1.7.2-keyed","dir":"keyed/jotai","keyed":true},{"name":"karyon-v1.1.3-keyed","dir":"keyed/karyon","keyed":true,"issues":[801]},{"name":"knockout-v3.5.0-keyed","dir":"keyed/knockout","keyed":true},{"name":"ko-jsx-v0.16.1-keyed","dir":"keyed/ko-jsx","keyed":true},{"name":"lighterhtml-v2.5.0-keyed","dir":"keyed/lighterhtml","keyed":true,"issues":[801]},{"name":"lit-v2.2.6-keyed","dir":"keyed/lit","keyed":true,"issues":[801]},{"name":"lit-html-v1.1.0-keyed","dir":"keyed/lit-html","keyed":true,"issues":[800,801]},{"name":"ls-element-v2.0.9-keyed","dir":"keyed/ls-element","keyed":true},{"name":"lui-v1.2.3-keyed","dir":"keyed/lui","keyed":true},{"name":"lwc-v2.7.3-keyed","dir":"keyed/lwc","keyed":true},{"name":"mahal-v1.4.0-keyed","dir":"keyed/mahal","keyed":true},{"name":"malina-v0.7.0-alpha-keyed","dir":"keyed/malina","keyed":true},{"name":"marionette-v5.0.0-alpha.2-keyed","dir":"keyed/marionette","keyed":true},{"name":"marionette-backbone-v5.0.0-alpha.2-keyed","dir":"keyed/marionette-backbone","keyed":true,"issues":[772]},{"name":"marko-v4.12.3-keyed","dir":"keyed/marko","keyed":true},{"name":"mikado-v0.7.64-keyed","dir":"keyed/mikado","keyed":true},{"name":"mimbl-v0.8.3-keyed","dir":"keyed/mimbl","keyed":true},{"name":"miso-v1.4.0-keyed","dir":"keyed/miso","keyed":true},{"name":"misojs-v1.1.0.0-keyed","dir":"keyed/misojs","keyed":true},{"name":"mithril-v2.0.4-keyed","dir":"keyed/mithril","keyed":true},{"name":"mobx-jsx-v0.14.0-keyed","dir":"keyed/mobx-jsx","keyed":true},{"name":"neverland-v3.3.2-keyed","dir":"keyed/neverland","keyed":true},{"name":"oldskull-v0.1.2-keyed","dir":"keyed/oldskull","keyed":true},{"name":"petit-dom-v0.2.0-keyed","dir":"keyed/petit-dom","keyed":true},{"name":"preact-v10.7.3-keyed","dir":"keyed/preact","keyed":true},{"name":"ractive-v1.3.6-keyed","dir":"keyed/ractive","keyed":true},{"name":"rax-v0.6.7-keyed","dir":"keyed/rax","keyed":true},{"name":"react-v17.0.2-keyed","dir":"keyed/react","keyed":true},{"name":"react-easy-state-v17.0.1 + 6.3.0-keyed","dir":"keyed/react-easy-state","keyed":true},{"name":"react-focal-v17.0.1 + 0.8.5-keyed","dir":"keyed/react-focal","keyed":true},{"name":"react-hooks-v18.2.0-keyed","dir":"keyed/react-hooks","keyed":true},{"name":"react-lab-v17.0.3-keyed","dir":"keyed/react-lab","keyed":true},{"name":"react-mlyn-v0.5.11-keyed","dir":"keyed/react-mlyn","keyed":true},{"name":"react-mobX-v17.0.1 + 5.15.4-keyed","dir":"keyed/react-mobX","keyed":true},{"name":"react-recoil-v17.0.1-keyed","dir":"keyed/react-recoil","keyed":true},{"name":"react-redux-v17.0.1 + 7.2.1-keyed","dir":"keyed/react-redux","keyed":true},{"name":"react-redux-hooks-v18.2.0 + 8.0.2-keyed","dir":"keyed/react-redux-hooks","keyed":true},{"name":"react-redux-hooks-immutable-v17.0.1 + 7.2.1-keyed","dir":"keyed/react-redux-hooks-immutable","keyed":true},{"name":"react-redux-rematch-v17.0.1 + 7.2.1 + 2.0.1-keyed","dir":"keyed/react-redux-rematch","keyed":true},{"name":"react-rxjs-v18.2.0 + 0.9.8-keyed","dir":"keyed/react-rxjs","keyed":true},{"name":"react-starbeam-v18.2.0 + 0.5.8-keyed","dir":"keyed/react-starbeam","keyed":true},{"name":"react-tagged-state-v18.2.0 + 1.5.0-keyed","dir":"keyed/react-tagged-state","keyed":true},{"name":"react-tracked-v17.0.1 + 1.6.0-keyed","dir":"keyed/react-tracked","keyed":true},{"name":"react-zustand-v17.0.1 + 3.7.2-keyed","dir":"keyed/react-zustand","keyed":true},{"name":"reagent-v0.10-keyed","dir":"keyed/reagent","keyed":true},{"name":"reaml-preact-v0.15.0 + 10.5.14-keyed","dir":"keyed/reaml-preact","keyed":true},{"name":"reaml-react-v0.15.0 + 17.0.1-keyed","dir":"keyed/reaml-react","keyed":true},{"name":"redom-v3.29.0-keyed","dir":"keyed/redom","keyed":true,"issues":[772]},{"name":"reflex-v0.8.4-keyed","dir":"keyed/reflex","keyed":true},{"name":"rescript-react-v0.10.3-keyed","dir":"keyed/rescript-react","keyed":true},{"name":"resonatejs-keyed","dir":"keyed/resonatejs","keyed":true},{"name":"riot-v6.1.2-keyed","dir":"keyed/riot","keyed":true},{"name":"s2-v1.0.0-keyed","dir":"keyed/s2","keyed":true,"issues":[800]},{"name":"san-v3.12.0-keyed","dir":"keyed/san","keyed":true,"issues":[800]},{"name":"san-composition-v3.10.1 + 1.1.0-keyed","dir":"keyed/san-composition","keyed":true,"issues":[800]},{"name":"scarlets-frame-v0.34.6-keyed","dir":"keyed/scarlets-frame","keyed":true},{"name":"sifrr-v0.0.5-keyed","dir":"keyed/sifrr","keyed":true,"issues":[800,801]},{"name":"sinuous-v0.28.1-keyed","dir":"keyed/sinuous","keyed":true,"issues":[800,801]},{"name":"skruv-v0.1.0-keyed","dir":"keyed/skruv","keyed":true},{"name":"solid-v1.4.4-keyed","dir":"keyed/solid","keyed":true},{"name":"solid-state-v1.4.4-keyed","dir":"keyed/solid-state","keyed":true},{"name":"stdweb-v0.4.17-keyed","dir":"keyed/stdweb","keyed":true,"issues":[772]},{"name":"stencil-v2.17.0-keyed","dir":"keyed/stencil","keyed":true},{"name":"svelte-v3.48.0-keyed","dir":"keyed/svelte","keyed":true},{"name":"sycamore-v0.7.1-keyed","dir":"keyed/sycamore","keyed":true},{"name":"uhtml-v3.0.1-keyed","dir":"keyed/uhtml","keyed":true,"issues":[772]},{"name":"uhydro-v1.0.7-keyed","dir":"keyed/uhydro","keyed":true},{"name":"ui5-webcomponents-v1.3.1-keyed","dir":"keyed/ui5-webcomponents","keyed":true},{"name":"valtio-v17.0.1 + 1.6.1-keyed","dir":"keyed/valtio","keyed":true},{"name":"vanillajs-keyed","dir":"keyed/vanillajs","keyed":true,"issues":[772]},{"name":"vanillajs-1-keyed","dir":"keyed/vanillajs-1","keyed":true,"issues":[772]},{"name":"vanillajs-wc-keyed","dir":"keyed/vanillajs-wc","keyed":true,"issues":[772]},{"name":"vidom-v0.11.0-keyed","dir":"keyed/vidom","keyed":true},{"name":"voby-v0.37.0-keyed","dir":"keyed/voby","keyed":true},{"name":"vue-v3.2.37-keyed","dir":"keyed/vue","keyed":true},{"name":"vuerx-jsx-v0.2.0-keyed","dir":"keyed/vuerx-jsx","keyed":true},{"name":"wasm-bindgen-v0.2.47-keyed","dir":"keyed/wasm-bindgen","keyed":true,"issues":[772]},{"name":"whatsup-v2.3.6-keyed","dir":"keyed/whatsup","keyed":true},{"name":"xania-v0.3.3-keyed","dir":"keyed/xania","keyed":true,"issues":[772]},{"name":"yew-v0.19.3-keyed","dir":"keyed/yew","keyed":true},{"name":"yew-hooks-v0.19.3-keyed","dir":"keyed/yew-hooks","keyed":true},{"name":"apprun-v2.28.3-non-keyed","dir":"non-keyed/apprun","keyed":false,"issues":[772]},{"name":"art-v0.1.7-non-keyed","dir":"non-keyed/art","keyed":false},{"name":"aurelia-v1.3.0-non-keyed","dir":"non-keyed/aurelia","keyed":false},{"name":"bdc-v1.0.0-non-keyed","dir":"non-keyed/bdc","keyed":false},{"name":"binding.scala-v10.0.1-non-keyed","dir":"non-keyed/binding.scala","keyed":false},{"name":"callbag-jsx-v0.0.29-non-keyed","dir":"non-keyed/callbag-jsx","keyed":false},{"name":"callbag-jsx-list-v0.0.29-non-keyed","dir":"non-keyed/callbag-jsx-list","keyed":false},{"name":"crui-v0.1.0-alpha.13-non-keyed","dir":"non-keyed/crui","keyed":false,"issues":[800]},{"name":"cyclejs-dom-v20.4.0-non-keyed","dir":"non-keyed/cyclejs-dom","keyed":false,"issues":[634]},{"name":"datum-v0.12.2-non-keyed","dir":"non-keyed/datum","keyed":false},{"name":"delorean-v0.1.0-non-keyed","dir":"non-keyed/delorean","keyed":false},{"name":"dojo-v8.0.0-non-keyed","dir":"non-keyed/dojo","keyed":false},{"name":"domdiff-v2.2.2-non-keyed","dir":"non-keyed/domdiff","keyed":false,"issues":[772]},{"name":"domvm-v3.4.12-non-keyed","dir":"non-keyed/domvm","keyed":false},{"name":"doohtml-non-keyed","dir":"non-keyed/doohtml","keyed":false,"issues":[772]},{"name":"doz-v3.4.1-non-keyed","dir":"non-keyed/doz","keyed":false,"issues":[800]},{"name":"ef-js-v0.13.12-non-keyed","dir":"non-keyed/ef-js","keyed":false},{"name":"elm-v0.19.1-3-non-keyed","dir":"non-keyed/elm","keyed":false},{"name":"endorphin-v0.5.2-non-keyed","dir":"non-keyed/endorphin","keyed":false},{"name":"etch-v0.14.1-non-keyed","dir":"non-keyed/etch","keyed":false},{"name":"fidan-v0.0.23-non-keyed","dir":"non-keyed/fidan","keyed":false,"issues":[772]},{"name":"fre-v2.5.1-non-keyed","dir":"non-keyed/fre","keyed":false},{"name":"halogen-v6.1.3-non-keyed","dir":"non-keyed/halogen","keyed":false},{"name":"heresy-v0.26.1-non-keyed","dir":"non-keyed/heresy","keyed":false},{"name":"hullo-v0.8.2-non-keyed","dir":"non-keyed/hullo","keyed":false},{"name":"hydro-js-v1.5.13-non-keyed","dir":"non-keyed/hydro-js","keyed":false},{"name":"imba-v1.5.2-non-keyed","dir":"non-keyed/imba","keyed":false},{"name":"inferno-v7.4.8-non-keyed","dir":"non-keyed/inferno","keyed":false},{"name":"lighterhtml-v2.5.0-non-keyed","dir":"non-keyed/lighterhtml","keyed":false},{"name":"lit-v2.1.1-non-keyed","dir":"non-keyed/lit","keyed":false},{"name":"lit-html-v1.1.0-non-keyed","dir":"non-keyed/lit-html","keyed":false,"issues":[800]},{"name":"literaljs-v7.0.2-non-keyed","dir":"non-keyed/literaljs","keyed":false},{"name":"maquette-v3.3.0-non-keyed","dir":"non-keyed/maquette","keyed":false},{"name":"mikado-v0.7.64-non-keyed","dir":"non-keyed/mikado","keyed":false},{"name":"mimbl-v0.8.3-non-keyed","dir":"non-keyed/mimbl","keyed":false},{"name":"miso-v1.4.0-non-keyed","dir":"non-keyed/miso","keyed":false},{"name":"moon-v1.0.0-beta.4-non-keyed","dir":"non-keyed/moon","keyed":false},{"name":"neow-v0.0.11-non-keyed","dir":"non-keyed/neow","keyed":false},{"name":"neverland-v3.3.2-non-keyed","dir":"non-keyed/neverland","keyed":false},{"name":"ractive-v1.3.6-non-keyed","dir":"non-keyed/ractive","keyed":false},{"name":"react-v16.8.6-non-keyed","dir":"non-keyed/react","keyed":false},{"name":"redom-v3.29.0-non-keyed","dir":"non-keyed/redom","keyed":false,"issues":[772]},{"name":"reflex-dom-v0.4-non-keyed","dir":"non-keyed/reflex-dom","keyed":false},{"name":"riot-v5.3.0-non-keyed","dir":"non-keyed/riot","keyed":false},{"name":"san-v3.12.0-non-keyed","dir":"non-keyed/san","keyed":false,"issues":[800]},{"name":"sauron-v0.50.3-non-keyed","dir":"non-keyed/sauron","keyed":false},{"name":"scarlets-frame-v0.34.6-non-keyed","dir":"non-keyed/scarlets-frame","keyed":false,"issues":[800]},{"name":"seed-v0.8.0-non-keyed","dir":"non-keyed/seed","keyed":false},{"name":"sifrr-v0.0.3-non-keyed","dir":"non-keyed/sifrr","keyed":false,"issues":[800]},{"name":"simi-v0.2.0-dev1-non-keyed","dir":"non-keyed/simi","keyed":false},{"name":"slim-js-v5.0.8-non-keyed","dir":"non-keyed/slim-js","keyed":false},{"name":"slingjs-v14.3.0-non-keyed","dir":"non-keyed/slingjs","keyed":false},{"name":"stdweb-v0.4.17-non-keyed","dir":"non-keyed/stdweb","keyed":false,"issues":[772]},{"name":"stem-v0.2.70-non-keyed","dir":"non-keyed/stem","keyed":false,"issues":[634]},{"name":"svelte-v3.48.0-non-keyed","dir":"non-keyed/svelte","keyed":false},{"name":"uhtml-v3.0.1-non-keyed","dir":"non-keyed/uhtml","keyed":false,"issues":[801]},{"name":"ui5-webcomponents-v1.3.1-non-keyed","dir":"non-keyed/ui5-webcomponents","keyed":false},{"name":"vanilla-dom-framework-v0.0.13-non-keyed","dir":"non-keyed/vanilla-dom-framework","keyed":false},{"name":"vanillajs-non-keyed","dir":"non-keyed/vanillajs","keyed":false,"issues":[772]},{"name":"vanillajs-1-non-keyed","dir":"non-keyed/vanillajs-1","keyed":false,"issues":[772]},{"name":"vue-v3.2.37-non-keyed","dir":"non-keyed/vue","keyed":false}];
export const benchmarks = [{"id":"01_run1k","label":"create rows","description":"creating 1,000 rows (5 warmup runs).","type":0,"allowBatching":true,"durationMeasurementMode":0},{"id":"02_replace1k","label":"replace all rows","description":"updating all 1,000 rows (5 warmup runs).","type":0,"allowBatching":true,"durationMeasurementMode":1},{"id":"03_update10th1k_x16","label":"partial update","description":"updating every 10th row for 1,000 rows (3 warmup runs). 16x CPU slowdown.","type":0,"throttleCPU":16,"allowBatching":true,"durationMeasurementMode":1},{"id":"04_select1k","label":"select row","description":"highlighting a selected row. (5 warmup runs). 16x CPU slowdown.","type":0,"throttleCPU":16,"allowBatching":true,"durationMeasurementMode":1},{"id":"05_swap1k","label":"swap rows","description":"swap 2 rows for table with 1,000 rows. (5 warmup runs). 4x CPU slowdown.","type":0,"throttleCPU":4,"allowBatching":true,"durationMeasurementMode":1},{"id":"06_remove-one-1k","label":"remove row","description":"removing one row. (5 warmup runs).","type":0,"allowBatching":true,"durationMeasurementMode":1},{"id":"07_create10k","label":"create many rows","description":"creating 10,000 rows. (5 warmup runs with 1k rows).","type":0,"allowBatching":true,"durationMeasurementMode":0},{"id":"08_create1k-after1k_x2","label":"append rows to large table","description":"appending 1,000 to a table of 10,000 rows. 2x CPU slowdown.","type":0,"throttleCPU":2,"allowBatching":true,"durationMeasurementMode":1},{"id":"09_clear1k_x8","label":"clear rows","description":"clearing a table with 1,000 rows. 8x CPU slowdown. (5 warmup runs).","type":0,"throttleCPU":8,"allowBatching":true,"durationMeasurementMode":1},{"id":"21_ready-memory","label":"ready memory","description":"Memory usage after page load.","type":1},{"id":"22_run-memory","label":"run memory","description":"Memory usage after adding 1,000 rows.","type":1},{"id":"23_update5-memory","label":"update every 10th row for 1k rows (5 cycles)","description":"Memory usage after clicking update every 10th row 5 times","type":1},{"id":"25_run-clear-memory","label":"creating/clearing 1k rows (5 cycles)","description":"Memory usage after creating and clearing 1000 rows 5 times","type":1},{"id":"26_run-10k-memory","label":"run memory 10k","description":"Memory usage after adding 10,000 rows.","type":1},{"id":"31_startup-ci","label":"consistently interactive","description":"a pessimistic TTI - when the CPU and network are both definitely very idle. (no more CPU tasks over 50ms)","property":"interactive","type":3},{"id":"32_startup-bt","label":"script bootup time","description":"the total ms required to parse/compile/evaluate all the page's scripts","property":"bootup-time","type":3},{"id":"33_startup-mainthreadcost","label":"main thread work cost","description":"total amount of time spent doing work on the main thread. includes style/layout/etc.","property":"mainthread-work-breakdown","type":3},{"id":"34_startup-totalbytes","label":"total kilobyte weight","description":"network transfer cost (post-compression) of all the resources loaded into the page.","property":"total-byte-weight","type":3}];
```

I can't spot anything strange in the keyed/non-keyed directories 🤔 The repo should be inline with the master branch apart from the changes in this PR, and whatever files got generated while running the tests and trying to update the table 🤔 I'll see if I can reinstall everything and still reproduce the problem when I'll have the time 👍 Thanks.

**Comment by krausest** [comment]
Hi @fabiospampinato , the 2nd last line contained two invalid entries: .DS_Store and compostate-jsx. The latter was removed some time ago (but git keeps directories with build artefacts).
I tried to improve directory scanning with commit https://github.com/krausest/js-framework-benchmark/commit/d63b632e7e0cfcd28bd048c7b23bddccabae597f.
You could pull, kill the server process, restart the server (`npm start`) and update the results (`npm run results`) and it should work. Does it?

**Comment by krausest** [comment]
Thanks. Here's the comparison:
Bildschirmfoto 2022-08-13 um 22 14 52

**Comment by fabiospampinato** [comment]
Reinstalling everything seemed to have fixed the issue 👍

**Pull request merged**
