### PR TITLE
Update RE:DOM to v3.0.2

### PR DESCRIPTION
**Pull request by pakastin**
"Remove row" test should now be ~3x faster!

### CODE REVIEW

**Comment by krausest** [comment]
Sorry - didn't have to time to merge your pull request yet. I'll try to find some time the next few days.

**Comment by pakastin** [comment]
No worries, I just resolved that new conflict for you to make it easier to merge 😉

**Comment by pakastin** [comment]
Should be ready to go without any hassle. At least I ran the tests and it worked allright – much faster than the previous version! 😎

**Comment by krausest** [comment]
Finally...
Results are [here](https://rawgit.com/krausest/js-framework-benchmark/964ae451d222ccc4de774fedeef7025c10227558/webdriver-ts-results/table.html)
Remove rows is much, much faster!
What's interesting is that the compare view shows that startup time improved significantly, but it seems like clear rows is a bit - but still significantly - slower (or I really need a review for my t-test #196  :smirk:) 
bildschirmfoto 2017-06-30 um 21 39 45

**Comment by pakastin** [comment]
Yeah, it's a small tradeoff. It's now doing the remove with lookup table instead of looping the DOM. It looks bad in your table (red), but if you compare to other frameworks it's not *that* bad (TOP 10!) 😀👍

Now: https://github.com/pakastin/redom/blob/master/src/list.js#L60-L68

Before: https://github.com/pakastin/redom/blob/master/src/setchildren.js#L29-L35

**Comment by pakastin** [comment]
Oh, and TOP 5 in memory allocation! I'm really happy with the results! 👌

Instead of micro-optimizations and clever tricks, I've wanted to keep the source clean and readable + let the browser do most of the work natively. It's proven that the DOM isn't slow after all, and that you can build a fast UI library with only 2 KB 😊

For example here's all the code for reordering child elements: https://github.com/pakastin/redom/blob/master/src/setchildren.js#L4-L36

Thanks for the merge, I've waited this anxiously! ✌️😎

**Comment by krausest** [comment]
Sorry I think you got me wrong - I guess I didn't explain that screenshot good enough. 
RE:DOM's performance is definitely really nice (and quite "green")
bildschirmfoto 2017-07-01 um 09 33 35
The screenshot I pasted is just a statistical comparison. Green values mean that a t-test shows that the "green framework" is statistically significant faster, and red means it's slower. The color displays the confidence level. A light green or red means the p-value is 10% and becomes darker when the p-value is smaller. But the color is absolutely no indications how much slower or faster the other is. 
Still one can e.g. say (as long as i did the t-test right) that re:dom is significantly faster than react for create rows (which sounds very sophisticated).
bildschirmfoto 2017-07-01 um 09 41 31

**Comment by pakastin** [comment]
I did understand. I just meant that the optimization to "remove one row" affected the "clear rows" slightly. It's always balancing between optimizations 🙂

Btw. it would be nice if "slowdown geometric mean" would be the default order instead of alphabetical.

**Pull request merged**
