### PR TITLE
chore: bump lwc to v6.6.1

### PR DESCRIPTION
**Pull request by nolanlawson**
We have another small optimization in this version. Thanks very much in advance! 🙇

### CODE REVIEW

**Comment by krausest** [comment]
I'm sorry, all PRs are currently blocked by https://github.com/krausest/js-framework-benchmark/issues/1655. Feel free to submit a PR for #1661 to get this PR merged 😄

**Comment by krausest** [comment]
Thanks - I hope to publish results for the PR tomorrow.

**Comment by nolanlawson** [comment]
Thank you for your hard work!! 🙇

**Comment by krausest** [comment]
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by nolanlawson** [comment]
Thanks a lot!! Really appreciate it. 🙇

**Pull request merged**
