### PR TITLE
upgrade Svelte to 5.0.0-next.33

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by birkskyum** [comment]
I think since the current version (next.8) that the svelte team abandoned this idea of using classes, so it would be great to have that update in the keyed/svelte example.

https://github.com/krausest/js-framework-benchmark/blob/d149b6593d3165e83ccbba9cf29d234e901258c1/frameworks/keyed/svelte/src/Main.svelte#L99-L104

**Comment by trueadm** [comment]
@birkskyum Nope. We still recommend classes for where they make sense and this is a great use-cases.

**Review by birkskyum — APPROVED** [review]

**Comment by trueadm** [comment]
Although we should probably update to alpha 35 now it's out before merging this. That contained some beefy internal changes.

**Comment by krausest** [comment]
I've already merged. But I'll push it to .35. Please don't update this PR.

**Comment by krausest** [comment]
Results are updated. Here's a comparison (left: keyed new results, right: keyed old results):
Screenshot 2024-01-14 at 11 42 32 AM
No real difference, but it's already damned fast...

**Pull request merged**
