### PR TITLE
add blockdom

### PR DESCRIPTION
**Pull request by ged-odoo**
This commit introduces the blockdom virtual dom in the list of frameworks. It is a virtual dom library, whose main idea is to use blocks as building blocks instead of individual htmlelements/textnodes. See the repository https://github.com/ged-odoo/blockdom for more information.

The implementation seems to work fine locally. I also ran `npm run index` to update the main list. If there is anything else that I should do to help get this in, please tell me!

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Results are updated:
Very impressive!

**Comment by gdeb** [comment]
Thank you! 
Now I need some magic to improve the select row benchmark :)

**Comment by ged-odoo** [comment]
Thank you

**Comment by ryansolid** [comment]
Good job. Truly exciting stuff.

**Comment by LucasLefevre** [comment]
Nice ! 😀

**Pull request merged**
