### PR TITLE
Updated Voby to v0.43.6

### PR DESCRIPTION
**Pull request by fabiospampinato**
Lots of internal tweaks, if I haven't messed anything up, which I'm not sure about, they might amount to something.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I'll push another update later today, I've found other optimizations 🤣

**Comment by fabiospampinato** [comment]
I've added just one extra optimizations, others didn't make enough of a difference.

**Comment by krausest** [comment]
Thanks, here's the comparison for the incremental update. Numbers are pretty close so it's hard to say whether it's actually faster:
Bildschirm­foto 2022-11-07 um 21 39 28

**Comment by fabiospampinato** [comment]
Thank you!

Yeah there isn't really that much room for improvement left for this benchmark anymore, there are only very minor tweaks left I think.

**Pull request merged**
