### PR TITLE
Adds React Hooks implementation

### PR DESCRIPTION
**Pull request by ryansolid**
Been playing around with Hooks a lot recently.  Super interested how this compares and if we can gain any performance insights. Would appreciate some review.

* I went with single state object since data and selected are mostly updated in unison.
* I used useCallback to only have the single fn ref on appendRows (when rows are added in different renders), but I wouldn't be surprised React.memo is slightly faster on its own.
* I didn't bother splicing array on update, not correct but works. Noticed React implementation doesn't either.
* Did a few less optimized patterns to feel idiomatic like react-redux implementation

### CODE REVIEW

**Comment by krausest** [comment]
Thanks, surely very interesting. I‘m on holidays this week and will merge it afterwards.

**Comment by thysultan** [comment]
@ryansolid Can we move `run`, `runLots`, `add`, `update`, `clear`, and `swapRows` into the memo  `Jumbotron`?

**Comment by ryansolid** [comment]
Is it good to pass naked setState into the child component? The state to be updated needs to owned by the main component. I've done similar in other fine grained libraries, but I'm unsure if it makes sense for React idiomatically.

I have no problem making this change, if you think that it makes sense.

**Comment by thysultan** [comment]
>Is it good to pass naked setState into the child component?

I'm unsure, my assumption is that since `setState` uses `useReducer` internally, it would be the same across renders, though this could just be a "current" implementation detail and may very well change, maybe @gaearon could comment in this.

**Comment by gaearon** [comment]
Generally `useReducer` + passing `dispatch` down via context is the recommended optimization approach. See https://github.com/ryardley/hooks-perf-issues/pull/3.

**Comment by ryansolid** [comment]
Ok, hard to argue with that.  I have updated the implementation. I might be over using useCallback and I'm banking on the fact the item.id never changes in the closure.

It does produce an interesting refactoring story when a user might start with setState, and then decides to delegate the commands to a child that is mostly static. I see this pattern happening fairly often as an optimization method.

**Comment by krausest** [comment]
Here are the results. All react contenders on the screenshot were re-run for a better comparison:
bildschirmfoto 2019-03-07 um 20 46 50

**Comment by ryansolid** [comment]
That's awesome,

My hunch was that that hooks should be the same or slightly better in performance and this confirms it. If even by a hair, Hooks are the most performant React variant.

But this is a really good demonstration of how optimized approaches for both React Hooks and Classes differ (looking at memory and performance characteristics).

Thanks @gaearon for the clarification on the recommended approach.

**Comment by tdd** [comment]
@gaearon any idea why swapping rows is so horrendously slow regardless of the approach? This is keyed, shouldn't that end up being just two `insertBefore` calls after a quick array traversal with referential comparison of keys?

**Comment by gaearon** [comment]
I think swapping two rows at the beginning and end is the worst case for React because it will `insertBefore` everything else. In this case React tries to be more predictable instead of unexpected perf jumps when a smarter heuristic didn't apply neatly. We could change but in practice we've rarely seen people care about in outside of benchmarks. If you're rendering 1000 rows and reorder them you should use virtualization in which case it's essentially free.

**Comment by tdd** [comment]
I was unconvinced by the main rationale (i.e. I failed to see why having keys didn't let us only move the two relevant lines DOM-side), then the virtualization note basically killed the whole argument 😁

**Pull request merged**
