### PR TITLE
feat(frameworks): add fastDom

### PR DESCRIPTION
**Pull request by PxyUp**
Good day!.
I added new reactive framework to yours benchmark
@krausest

### CODE REVIEW

**Comment by krausest** [comment]
Looks keyed. Why didn't you submit it as a keyed framework?
Please let me know if you also think it's keyed - I'd move it in the keyed folder then.

**Comment by PxyUp** [comment]
@krausest I am fine with that. i am check vuejs code and found just difference in provide keyFn in `v-for` keyed provide, non-keyed not. 
If need i will update MR

**Comment by PxyUp** [comment]
@krausest Done

**Comment by krausest** [comment]
Thanks. Definitely not bad! 
Bildschirmfoto 2019-04-11 um 21 20 06

**Comment by PxyUp** [comment]
@krausest  thanks you

**Pull request merged**
