### PR TITLE
Update cample to v3.2.0-beta.8

### PR DESCRIPTION
**Pull request by antonmak1**
Overall, I think I've fixed a lot of bugs now that were slowing down results. Perhaps now it will be possible to fix “select row” and make the results for this test satisfactory. I believe that the syntax of the framework will allow the results to reach even the level of 1.04-1.06, but it feels like the code is at level 1.08-1.10 now. Next, it will be necessary to redo the assembly of templates, I think this is already work for about a couple of weeks or months, so I hope the next pull request for the test will be in 2024 (I think I didn’t break anything. I tested , but who knows what could break there).

Thank you very much for devoting your time to review and test the implementation of this framework. Happy New Year 2024!

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Here's a screenshot from the results (left new/updated keyed version, right old keyed version):
Screenshot 2023-12-23 at 4 22 57 PM
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by antonmak1** [comment]
> Thanks. Here's a screenshot from the results (left new/updated keyed version, right old keyed version): Screenshot 2023-12-23 at 4 22 57 PM [Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

strange, is this really a new version? On my computer it shows faster

**Comment by krausest** [comment]
I tweaked my build process some time ago to make sure a git pull is always performed before running locally. That aside I can't remember that the build didn't work or got something wrong (it's pretty much automated, deletes the whole node_modules and dist folders and performs a clean install).

Nevertheless I rebuilt and ran again:
On the left new keyed version, on the right the old version:
Screenshot 2023-12-23 at 5 52 56 PM
Sorry, didn't improve on my machine.

**Comment by antonmak1** [comment]
> I tweaked my build process some time ago to make sure a git pull is always performed before running locally. That aside I can't remember that the build didn't work or got something wrong (it's pretty much automated, deletes the whole node_modules and dist folders and performs a clean install).
> 
> Nevertheless I rebuilt and ran again: On the left new keyed version, on the right the old version: Screenshot 2023-12-23 at 5 52 56 PM Sorry, didn't improve on my machine.

OK. Happens. This means I need to work more diligently on the code. Thanks you!

**Pull request merged**
