### PR TITLE
korvin framework benchmark setup

### PR DESCRIPTION
**Pull request by Niedzwiedzw**
this is the framework that I mentioned in this issue
https://github.com/krausest/js-framework-benchmark/issues/1442

I'm sorry for the delay, but as I said it's a toy project and I needed to do some cleanup before publishing it.

### CODE REVIEW

**Comment by krausest** [comment]
The real duration for create rows for your framework should be about 62 msecs. The benchmark indeed reports a wrong value since there's a large duration betwen mousedown and click.
I suppose you're performing the redraw already on the mousedown event and not on the click event. 
Can you check why the click event is fired so late for your framework and change it to handle the click event?
Screenshot 2023-10-21 at 10 00 15 PM
You must zoom in and scroll to the right to find the click event:
Screenshot 2023-10-21 at 10 01 50 PM

**Comment by Niedzwiedzw** [comment]
ok let me modify the implementation

**Comment by Niedzwiedzw** [comment]
image
damn... @krausest

**Comment by Niedzwiedzw** [comment]
image
yeah that's more realistic - false alarm!

**Comment by krausest** [comment]
Do you want me to merge the PR?

**Comment by Niedzwiedzw** [comment]
yeah it'd be cool :)

**Comment by krausest** [comment]
It's now included in the [results](https://krausest.github.io/js-framework-benchmark/current.html).

**Pull request merged**
