### PR TITLE
glimmer update (perf improvements)

### PR DESCRIPTION
**Pull request by lifeart**
Should be at least 5x performant on row swaps, due to https://github.com/glimmerjs/glimmer-vm/pull/945

image

### CODE REVIEW

**Comment by lifeart** [comment]
@simonihmig could you double check results?

**Comment by lifeart** [comment]
image

**Comment by simonihmig** [comment]
> could you double check results?

currently flooded with work, so sorry no. But looks awesome!

**Comment by krausest** [comment]
Thanks. Results have been [updated](https://krausest.github.io/js-framework-benchmark/current.html).

**Pull request merged**
