### PR TITLE
updated to remove 772 error and pass the iskeyed test

### PR DESCRIPTION
**Pull request by yysun**

### CODE REVIEW

**Comment by krausest** [comment]
Thanks! I think it's a great step for AppRun to get rid of #772. 
But I think I must mark it for using explicit event delegation #801 in the click function (which is a much minor issue than #772) . 
Would you concur?

**Comment by yysun** [comment]
I agree with you and thank you very much.

**Comment by krausest** [comment]
Thanks - results are updated. Here's the table with the latest updates:

**Comment by yysun** [comment]
Awesome, thanks!

**Pull request merged**
