### PR TITLE
Optimize Ember app, to prevent creating unnecessary empty text nodes

### PR DESCRIPTION
**Pull request by simonihmig**
Seems to have a significant positive effect on render times (given the many iterations)

/cc @NullVoxPopuli

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
@simonihmig, do you have screenshots? :(

**Comment by simonihmig** [comment]
> do you have screenshots?

You mean of the results table, or of what?

For the results I just compared the files in `webdriver-ts/results` with previous runs without that change...

**Comment by NullVoxPopuli** [comment]
Yeah, just something showing how much of a difference this PR makes?

**Comment by simonihmig** [comment]
Some of the observed changes (though just with a test count of 5, so probably not very precise):

- run1k: 598 -> 460
- swap: 560 -> 527
- create10k: 3576 -> 2778

**Comment by krausest** [comment]
Thanks. Indeed a bit faster. I noticed and removed an unnecessary style="cursor: pointer" on the first a-element in each row:
bildschirmfoto 2019-01-08 um 21 47 01

**Pull request merged**
