### PR TITLE
DooHTML-DOM-v0.92.1-beta

### PR DESCRIPTION
**Pull request by hman61**
Fixed minor issue in attribute parser

### CODE REVIEW

**Comment by krausest** [comment]
Hmmm - got a funny error:
```
doohtml-non-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' and keyed for 'swap rows benchmark' . It'll appear as keyed in the results
ERROR: Framework doohtml-non-keyed is not correctly categorized
```
It's no shame having no non-keyed implementation (vs. vice versa). Can we just merge the keyed implementations and remove the non-keyed?

**Comment by hman61** [comment]
Yes please. you can skip the non-keyed

**Comment by hman61** [comment]
I will revert the non-keyed shortly

**Comment by krausest** [comment]
Left is the new version, on the right the old:
Screenshot 2023-10-25 at 10 38 33 PM

**Pull request merged**
