### PR TITLE
Add Inferno + MobX benchmark

### PR DESCRIPTION
**Pull request by tkrotoff**
Ping @mweststrate @trueadm

### CODE REVIEW

**Comment by trueadm** [comment]
@tkrotoff could you possibly use Inferno 1.0.0-beta21? 0.7 is very old now and will soon be ancient :) ping me if you want some help using it.

**Comment by tkrotoff** [comment]
@trueadm I've copy-pasted package.json from the Inferno benchmark => identical versions

**Comment by trueadm** [comment]
@tkrotoff ah sorry, I completely misread the version – just ignore me :) what results did you get out of curiosity?

**Comment by tkrotoff** [comment]
@trueadm results (runned inside a Ubuntu VM while working):

screen shot 2016-11-30 at 16 27 52

I guess the day MobX uses [Proxy object](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) (see [#652](https://github.com/mobxjs/mobx/issues/652)) it will be faster/use less memory and provide a better API.

**Comment by tkrotoff** [comment]
Any news on this?

**Comment by nightwolfz** [comment]
@tkrotoff With the release of inferno v1, this benchmark should be updated again :)

**Comment by leeoniya** [comment]
@nightwolfz can you guys also submit a keyed implementation?

**Comment by tkrotoff** [comment]
> this benchmark should be updated again

Won't update it if it's not going to be merged...

**Comment by krausest** [comment]
I'm hesitating to merge it (similar to #45, although impact of mobx was smaller then). There are already a very large number of frameworks. What unique benefit do you see by adding inferno + mobx?

**Comment by tkrotoff** [comment]
> What unique benefit do you see by adding inferno + mobx?

I wanted to see if MobX could benefit from Inferno good performance claims (like Inferno+Redux benchmark).

Since MobX is very popular ([221,096 downloads in the last month](https://www.npmjs.com/package/mobx), [first release in 2015](https://github.com/mobxjs/mobx/tags?after=0.1.3)), I guess I'm not the only one interested by this benchmark.
Its NPM popularity is equivalent to Vue.js ([236,387 downloads](https://www.npmjs.com/package/vue), [~2013](https://github.com/vuejs/vue/tags?after=v0.7.6)) and Ember.js ([232,811 downloads](https://www.npmjs.com/package/ember-cli), [~2011](https://github.com/emberjs/ember.js/tags?after=v0.9.2)).

=> so yes, IMHO MobX deserves to get benchmarks with the 2 most popular VDOM implementations compatible with it.


PS:
MobX is more popular than Aurelia ([18,432 downloads](https://www.npmjs.com/package/aurelia-framework)), Inferno ([18,061 downloads](https://www.npmjs.com/package/inferno)), Preact ([16,661 downloads](https://www.npmjs.com/package/preact)), Riot ([13,681 downloads](https://www.npmjs.com/package/riot)), Ractive ([11,317 downloads](https://www.npmjs.com/package/ractive)), Mithril ([5,257 downloads](https://www.npmjs.com/package/mithril)), Bobril ([1,502 downloads](https://www.npmjs.com/package/bobril)), domvm ([261 downloads](https://www.npmjs.com/package/domvm)), Kivi ([152 downloads](https://www.npmjs.com/package/kivi)) and all other experimental VDOM implementations included in this benchmark (that most probably no one will ever use except their authors - no offense here).
If you are afraid there is too many frameworks in your benchmark, you should start here...

Redux is about [1,303,720 downloads last month](https://www.npmjs.com/package/redux).

**Comment by leeoniya** [comment]
i'll put in my two cents. (i know, no one asked)

this benchmark is not a state management lib benchmark. nor is it a popularity contest. the rules of this bench allow you to bring your own datastore implementation, but it only matters insofar as the *improve* performance, not incur overhead (as most of them do).

there are an innumerable quantity of permutations of ui libs + state management libs since many can be used with each other. i would instead argue for also removing the redux variants *unless* they improve perf of the base UI lib...it's likely that none actually will unless their immutability guarantees come super cheap.

there's certainly room for a separate and useful benchmark that shows perf of popular combos of state libs and ui libs, but they don't belong in the same table as the rest, only adding clutter, IMHO.

**Comment by tkrotoff** [comment]
@leeoniya
To sum up: as a VDOM dev you're interested in VDOM implementations benchmarks.

Most of the time end users use a state management lib above a VDOM. So you want your VDOM implementation to perform well with popular state management libs.

**Comment by leeoniya** [comment]
@tkrotoff 
certainly, i'm not unbiased. however, if you were to use MobX with all of the existing libs (includijg vanilla) you would end up with exactly the same table. my point is that it's a fixed overhead which can easily be comminucated with a single statement for all libs: "add X% perf overhead and Y% mem overhead for MobX v2.6.3".

Adding a state management lib adds yet another factor that, while useful to know, is unnecessary makes a straightforward benchmark more cluttered and harder to interpret. I'm not saying it shouldn't exist at all, just not in the same table.

**Comment by localvoid** [comment]
@leeoniya 

>if you were to use MobX with all of the existing libs (includijg vanilla) you would end up with exactly the same table. my point is that it's a fixed overhead which can easily be comminucated with a single statement for all libs: "add X% perf overhead and Y% mem overhead for MobX v2.6.3".

It is actually slightly more complicated. When mobx or redux is added, it is way much harder to optimize code paths that specific to benchmarks and get impressive results. With some libraries, adding mobx can reveal something that their authors are trying to hide when they trying to convince everyone that they've implemented the fastest web ui library ;)

**Comment by leeoniya** [comment]
@localvoid 

> With some libraries, adding mobx can reveal something that their authors are trying to hide

can't tell if you actually have some specific impl in mind or just trolling, with yoir winkie faces ;) this bench is in much better shape now that it has been since the beginning.

**Comment by krausest** [comment]
I'm closing this PR. I don't want to turn this more into a app state benchmark (it's already enough for react).

**Pull request closed without merging**
