### PR TITLE
feat: add alins

### PR DESCRIPTION
**Pull request by theajack**
Add [alins](https://github.com/alinsjs/alins) benchmark

### CODE REVIEW

**Comment by krausest** [comment]
Looks like the keyed implementation isn't correct
```
npm run isKeyed -- keyed/alins non-keyed/alins
...
Keyed test for swap failed. Expected at least 1 added and 1 removed TR, but there were 0 added and 0 removed
Keyed test for create rows failed. Expected that 1000 TRs should be removed and added, but there were 0 added TRs and 0 were removed

**Comment by theajack** [comment]
@krausest Removed the keyed implementation of Alins

**Comment by theajack** [comment]
@krausest Thanks for your review. Alins is a non-key type framework, and the implementation under the keyed directory has been removed.

**Comment by krausest** [comment]
Thanks. [Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Pull request merged**
