### PR TITLE
Upgrade Vue to 3.4

### PR DESCRIPTION
**Pull request by filipsobol**

### CODE REVIEW

**Comment by krausest** [comment]
For some reasons I don't understand it doesn't produce a valid output:
```
main.js:2 Uncaught ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined
    at main.js:2:51258
    at main.js:2:62838
```
Updating didn't help, going back to 3.3.4 creates a working js file.

**Comment by JereMiO** [comment]
Maybe @yyx990803 has a solution ?

**Comment by krausest** [comment]
Adding the following to webpack.config helps:
```
		new webpack.DefinePlugin({
			__VUE_PROD_DEVTOOLS__: JSON.stringify(false)
		})			

```
(found on https://stackoverflow.com/questions/67975438/referenceerror-vue-prod-devtools-is-not-defined).
I hope to post the results tomorrow.

**Comment by krausest** [comment]
Here's a comparison (left updated key version, right old versions + jsx version):
Screenshot 2024-01-03 at 8 07 27 PM

**Pull request merged**
