### PR TITLE
Fix incr_dom build

### LINKED ISSUE #957: incr_dom build is broken
Builing incr_dom fails in the docker container and locally.
The following error occurs in the docker build:
```
> esy @esy install

info install 0.6.7 (using esy.json)
info fetching: done                                                                                    
error command failed: 'tar' 'xf' '/build/frameworks/non-keyed/incr_dom/_esy/default/dist/e7eda1500b589a2f164a69a4e04e32d0' '-C' '/tmp/esy-909b1a'
      stderr:
               tar (child): lbzip2: Cannot exec: No such file or directory
               tar (child): Error is not recoverable: exiting now
               tar: Child returned status 2
               tar: Error is not recoverable: exiting now
               
      stdout:
               
error command failed: 'tar' 'xf' '/build/frameworks/non-keyed/incr_dom/_esy/default/dist/ac13f24928fd8c3868f7141f9da38033' '-C' '/tmp/esy-0168cc'
      stderr:
               tar (child): lbzip2: Cannot exec: No such file or directory
               tar (child): Error is not recoverable: exiting now
               tar: Child returned status 2
               tar: Error is not recoverable: exiting now
               
      stdout:
               
error: error running command                  
  unpacking @opam/dune@opam:2.7.1
  installing @opam/dune@opam:2.7.1
esy: exiting due to errors above
```

and the following is the results in Fedora 35:
```
    make[3]: Entering directory '/home/stefan/.esy/3/b/ocaml-4.9.1000-ffe51dac/runtime'
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o startup_aux_n.o startup_aux.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o startup_nat_n.o startup_nat.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o main_n.o main.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o fail_nat_n.o fail_nat.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o roots_nat_n.o roots_nat.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o signals_n.o signals.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o signals_nat_n.o signals_nat.c
    gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common -fno-tree-vrp -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/home/stefan/.esy/3___________________________________________________________________/s/ocaml-4.9.1000-ffe51dac/lib/ocaml"'  -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o misc_n.o misc.c
    signals_nat.c:185:13: error: variably modified 'sig_alt_stack' at file scope
      185 | static char sig_alt_stack[SIGSTKSZ];
          |             ^~~~~~~~~~~~~
    make[3]: *** [Makefile:343: signals_nat_n.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    make[3]: Leaving directory '/home/stefan/.esy/3/b/ocaml-4.9.1000-ffe51dac/runtime'
    make[2]: *** [Makefile:1002: makeruntimeopt] Error 2
    make[2]: Leaving directory '/home/stefan/.esy/3/b/ocaml-4.9.1000-ffe51dac'
    make[1]: *** [Makefile:415: opt.opt] Error 2
    make[1]: Leaving directory '/home/stefan/.esy/3/b/ocaml-4.9.1000-ffe51dac'
    make: *** [Makefile:466: world.opt] Error 2
    error: command failed: './esy-build' (exited with 2)
    esy-build-package: exiting with errors above...
    
  building ocaml@4.9.1000
esy: exiting due to errors above
```

### PR DESCRIPTION
**Pull request by vthemelis**
Aims to fix #957

* Upgrade the versions of various dependencies
* Force compiling to OCaml bytecode so that js_of_ocaml can transpile that to JS

### CODE REVIEW

**Comment by vthemelis** [comment]
@krausest, is there a CICD plan that I can run for this PR? It seems to be working fine for me locally.

**Comment by krausest** [comment]
Sorry, currently there's no CI build. I had that, but it had less benefits than I hoped.

I ran into two issues so I added esy as an dependency again and then I installed lbzip2. After that it built.

**Comment by vthemelis** [comment]
Cool! Would you like to push your changes?

**Comment by krausest** [comment]
Yes, I just got interrupted and I hope to update results tomorrow and merge it then.

**Pull request merged**
