### PR TITLE
Improve accuracy of CPU-bound benchmarks

### PR DESCRIPTION
**Pull request by syduki**
The rationale behind this is that running multiple iterations of a benchmark within the same tab can distort the results due to optimization strategies in the browser. Consequently, this introduces an unreliable variance when comparing different types of frameworks, whether by nature (compiled vs runtime) or by behavior (e.g., innerHTML vs createElement).
This aligns with my observations, where certain frameworks lag behind others in some scenarios, even when using manual DOM manipulations.

To observe the impact of this change a small experiment was run in the following environment:

HW: HP EliteBook 8470p, i5-3320M × 4, 16.0 GiB
SW: Ubuntu 23.04, Chromium 118.0.5993.70 (Official Build) snap (64-bit)

Given the constraints of low-spec hardware, I opted for a minimal set of well-known (keyed) frameworks. The *vanillajs-1* serves as the control benchmark. Additionally, the [karyon](https://github.com/krausest/js-framework-benchmark/tree/master/frameworks/keyed/karyon) framework, which I maintain and am familiar with regarding its behavior under various test scenarios, was included in the selection.

The benchmark figures are below:

- using page reload between iterations (current):

cpu-benchmark-old

and the [results.ts](https://github.com/krausest/js-framework-benchmark/files/12921375/results.ts.old.zip).

- using new page between iterations (modified):

cpu-benchmark-new

and the [results.ts](https://github.com/krausest/js-framework-benchmark/files/12921373/results.ts.new.zip).

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. I'll take a look at it. Which results do you find the most striking? Alpine create rows or something else?

**Comment by fabiospampinato** [comment]
Interesting how Karyon seems to be significantly more affected than the others by the change 🤔

**Comment by krausest** [comment]
I took a look at it and I'm not so sure...
We definitely need a metric to determine wether accuracy is higher when a new page is opened per benchmark iteration (your proposal) instead of when one benchmark iteration is performed in one page (implemented version).
I suggest that we use the sum of squares as the metric to decide: sum[(duration for benchmark iteration - mean for benchmark and framework)^2].

I chose the following frameworks (pretty similar to your choice above):
['alpine-v3.12.0-keyed', 'anansi-v0.14.0-keyed', 'angular-cf-v17.0.0-rc.0-keyed', 'angular-ngfor-v17.0.0-rc.0-keyed', 'inferno-v8.2.2-keyed', 'ivi-v3.0.0-keyed', 'lit-v3.0.0-keyed', 'preact-classes-v10.13.1-keyed', 'react-v18.2.0-keyed', 'react-hooks-v18.2.0-keyed', 'solid-v1.8.0-keyed', 'svelte-v4.0.0-keyed', 'sycamore-v0.9.0-beta.2-keyed', 'uhtml-v3.2.1-keyed', 'vanillajs-keyed', 'voby-v0.48.0-keyed', 'vue-v3.3.4-keyed', 'wasm-bindgen-v0.2.84-keyed']

Sum of squares for the new implementation (new page per iteration):
sum of squares for webdriver-ts/results_sumsquares_new and 01_run1k: 314.92891733333335
sum of squares for webdriver-ts/results_sumsquares_new and 02_replace1k: 551.9059909333336
sum of squares for webdriver-ts/results_sumsquares_new and 03_update10th1k_x16: 205.10238533333342
sum of squares for webdriver-ts/results_sumsquares_new and 04_select1k: 169.03058983999998
sum of squares for webdriver-ts/results_sumsquares_new and 05_swap1k: 606.8691998666666
sum of squares for webdriver-ts/results_sumsquares_new and 06_remove-one-1k: 202.6347252000001
sum of squares for webdriver-ts/results_sumsquares_new and 07_create10k: 14413.777205733328
sum of squares for webdriver-ts/results_sumsquares_new and 08_create1k-after1k_x2: 221.21344626666672
sum of squares for webdriver-ts/results_sumsquares_new and 09_clear1k_x8: 150.18832746666666
Sum of squares total for webdriver-ts/results_sumsquares_new : 16835.650787973325

Sum of squares for the old implementation (new page per benchmark):
sum of squares for webdriver-ts/results_sumsquares_old and 01_run1k: 242.88264213333332
sum of squares for webdriver-ts/results_sumsquares_old and 02_replace1k: 352.53603626666666
sum of squares for webdriver-ts/results_sumsquares_old and 03_update10th1k_x16: 412.1191811999999
sum of squares for webdriver-ts/results_sumsquares_old and 04_select1k: 145.1237332
sum of squares for webdriver-ts/results_sumsquares_old and 05_swap1k: 752.8689664000001
sum of squares for webdriver-ts/results_sumsquares_old and 06_remove-one-1k: 284.18701120000003
sum of squares for webdriver-ts/results_sumsquares_old and 07_create10k: 8304.411788666663
sum of squares for webdriver-ts/results_sumsquares_old and 08_create1k-after1k_x2: 220.26893653333332
sum of squares for webdriver-ts/results_sumsquares_old and 09_clear1k_x8: 162.22621959999998
Sum of squares total for webdriver-ts/results_sumsquares_old : 10876.624515199996

As you can see the sum of squares is lower for the old implementation. If we look at each benchmark we seen update 10th standing out. 

My current conclusion: Except for update 10th row your proposal is worse for accuracy. It could be interesting to check if we could indeed improve accuracy by using new page per iteration for update 10th row. 

I can provide some python scripts if someone wants to investigate.

**Comment by leeoniya** [comment]
> ...suggests that the browser is not the only variable here and the environment (HW/SW) also plays it's role in the benchmark.

fwiw, this is true of every benchmark that has ever been written.

**Comment by krausest** [comment]
I tried for the chrome 119 numbers (actual=same tab, probe=new tab):
```
total_variance_per_scenario: {
  '01_run1k': { actual: 288.8817823142857, probe: 243.49750913333344 },
  '02_replace1k': { actual: 319.02374380952386, probe: 278.0641292952382 },
  '03_update10th1k_x16': { actual: 957.3278442857146, probe: 519.5212925714286 },
  '04_select1k': { actual: 126.82963652666672, probe: 92.45575704333334 },
  '05_swap1k': { actual: 957.6544103238094, probe: 659.5528565047621 },
  '06_remove-one-1k': { actual: 247.7073512476191, probe: 126.67321120000004 },
  '07_create10k': { actual: 39693.03699246666, probe: 37827.02893817143 },
  '08_create1k-after1k_x2': { actual: 499.0531258571429, probe: 408.69639880952377 },
  '09_clear1k_x8': { actual: 177.88484760952383, probe: 122.45087591428567 },
}
global_variance: { actual: 43267.39973444094, probe: 40277.940968643336 }
deviation: { actual: 769, probe: 410, equal: 0 }

``` 
So in this run it looked indeed better for your suggestion in all cases!

There's one caveat: I'm currently seeing a few errors where the trace is mostly empty (the error says that no click event is included in the trace). I had 5 such errors for the same tab approach and 35 for the new tab approach. I currently have no idea how to mitigate this error. If I find something we might switch to the new tab approach.

**Comment by krausest** [comment]
As per #1493 I'm closing it here, similar functionality was integrated in master.

**Pull request closed without merging**
