### PR TITLE
chore: update keyed framework lockfiles to v3

### PR DESCRIPTION
**Pull request by nakrovati**
I did two things:
- Updated lockfiles to v3 at frameworks in keyed. 
- Added a script to update lockfiles in the future when a new version of package-lock.json is released.

### CODE REVIEW

**Comment by krausest** [comment]
I hurried to merge this PR to avoid merge conflicts :)

**Comment by nakrovati** [comment]
Я как раз сделал его ночью, потому что никто ночью не делает PR.  Я проверял.

**Comment by nakrovati** [comment]
I just did it at night, because no one does PR at night.  There are no conflicts with my open PRs, I checked.

**Comment by nakrovati** [comment]
There are no conflicts with PR Van and Elmish merge, because  they don't update package-Lock.json.

**Pull request merged**
