### PR TITLE
update vue-vapor

### PR DESCRIPTION
**Pull request by sxzz**
Vue Vapor's performance has improved.

### CODE REVIEW

**Comment by krausest** [comment]
Here's a screenshot from an incremental run (left new version, right old version).
Please note that vanillajs was slower on the left. I'm a bit disappointed with that because I'm trying to solve https://github.com/krausest/js-framework-benchmark/issues/1721, but as you can see vanillajs perfomed was 0.2 slower (even after reboot and on AC). So I think it's plausible to assume that performance for all updated versions would be better in a full run. Vue-vapor was faster even under those circumstances.
Screenshot 2024-09-25 at 08 05 07

**Comment by antonmak1** [comment]
@sxzz Hi! It's really cool that you're promoting a topic without VDOM! I was so blown away by this comment, like VDOM isn't crap, that it's fast, it's just that js-framework-benchmark is a disgrace that it's being compared to it in terms of speed. It's just mind-blowing.

**Comment by antonmak1** [comment]
@sxzz Like, I just came across this comment and was just shocked. https://x.com/dan_abramov2/status/1796156983575232942

**Comment by antonmak1** [comment]
@krausest It turns out that the benchmark is crap, that's how it is, it doesn't show the speed. It's a shame what we're doing. I'm just shocked. This stinking VDOM is being promoted to the masses tightly, then billions of people load the site a second or two faster, and that's millions of years of time saved for people.

**Comment by antonmak1** [comment]
For convenience, people simply waste millions of seconds of time that could be saved.

**Pull request merged**
