### PR TITLE
Update Sinuous v0.12.6

### PR DESCRIPTION
**Pull request by luwes**
Shouldn't affect performance too much, might be a bit faster because

- `map` uses an Array instead of Map to keep track of the disposers
- in `map` full replace used to use a loop of `removeChild` calls instead of a simple `.textContent = ''` to clear which is possible since there are no sibling elements.

### Fixed

- Fixed naming issue for umd and iife bundles
- Add observable duplicate edges check
- Replace Map w/ array for `map` disposers

### Fixed

- Fixed [Plain array in root doesn't return `DocumentFragment` #19](https://github.com/luwes/sinuous/issues/19)

### Fixed

- Fixed [template` inserts with duplicate value are empty #14](https://github.com/luwes/sinuous/issues/14)

### Fixed

- Fixed [Incorrect updating of observable #18](https://github.com/luwes/sinuous/issues/18)

### Changed

- Upgraded `sinuous/htm` and `sinuous/babel-plugin-htm` to latest version.

### Added

- Added support for plain array inserts again w/ no size increase.

### Changed

- Make `map` return a DocumentFragment.
- Optimized and re-used code for full replace in `map`.

### Added

- Added SVG support.

### Removed

- Removed plain array inserts. Fragments can be used for this aka

```js
  html` 
    <h1>Title</h1>
    <p>Some text</p>
  `
```

### CODE REVIEW

**Comment by ryansolid** [comment]
> in map full replace used to use a loop of removeChild calls instead of a simple .textContent = '' to clear which is possible since there are no sibling elements.

This should be noticeable difference. I had a bug a few versions back I wonder if that had propagated into your codebase and you never got the fix.

**Comment by luwes** [comment]
@ryansolid I think it might have been in this commit
https://github.com/luwes/sinuous/commit/a9036e508a14ccf57ecf7fc70bd8ad749f443ad9

**Comment by ryansolid** [comment]
Yeah, that was all you. In any case, I think that should be a nice boost in benchmark 2.

**Comment by krausest** [comment]
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated. No need to look far to the right :+1: !

**Pull request merged**
