### PR TITLE
Updated deleight to v5.5.8. It is not broken now. Cheers....

### PR DESCRIPTION
**Pull request by mksunny1**
I have updated the deleight implementation to use the latest version (v5.5.8). Now everything is working again. Not much is changed except restructuring the whole library to be cleaner and more modular. Also abstracted many common patterns I observed in my code for easy reuse.

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Since I'm updating all (keyed) frameworks I'll post a full run the next days or weeks.

**Comment by krausest** [comment]
Could you please update the non-keyed version, too?

**Comment by mksunny1** [comment]
Sure. I will do that between today and tomorrow.

**Comment by mksunny1** [comment]
@krausest I have now updated the non-keyed implementation. The change is part of the currently open pull request, so I have not created a new one. 

Merry Xmas...

**Pull request merged**
