### PR TITLE
feat: add effector-react

### PR DESCRIPTION
**Pull request by sergeysova**

### CODE REVIEW

**Comment by sergeysova** [comment]
@krausest ?

**Comment by krausest** [comment]
Sorry, I‘m a bit short of time. Maybe I find the time this weekend.

**Comment by krausest** [comment]
Sorry, bad news. React-effector is tapping into issue #694
```
npm run isKeyed -- --headless keyed/effector-react
Keyed test for swap failed. Swap must add the TRs that it removed, but there were 2 new nodes
```
This issue turned up not too long ago, so there are still a few frameworks that don't behave correctly, but I plan to push them into the non-keyed section of the table at some point in time.

Can you take a look at it and see if you can make it truly keyed?

**Comment by krausest** [comment]
Closing this PR due to inactivity. Please open a new PR when you've prepared a new implementation.

**Pull request closed without merging**
