### PR TITLE
add reaml-react and reaml-preact

### PR DESCRIPTION
**Pull request by utkarshkukreti**
[Reaml](https://github.com/utkarshkukreti/reaml) is an OCaml/BuckleScript wrapper for React. My goal for submitting this is to show the overhead (both perf and size) vs optimized JS + React and JS + Preact to potential users.

Please let me know if I missed any step of the contributing guide!

(The canonical implementation of this lives [in the Reaml repo](https://github.com/utkarshkukreti/reaml/blob/master/examples/Jfb.ml); this is a copy of that file.)

(follow up to #699)

### CODE REVIEW

**Comment by krausest** [comment]
I'm getting the following error - can you please take a look at it?
```
> jfb-reaml-preact@0.0.0 build-prod /build/frameworks/keyed/reaml-preact
> bsb -clean-world && bsb -make-world && rollup -c --environment production

File "/build/frameworks/keyed/reaml-preact/bsconfig.json", line 1
Error: Invalid json format
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jfb-reaml-preact@0.0.0 build-prod: `bsb -clean-world && bsb -make-world && rollup -c --environment production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jfb-reaml-preact@0.0.0 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T19_43_20_671Z-debug.log
child_process.js:669
    throw err;
    ^

Error: Command failed: npm install && npm run build-prod

```

**Comment by utkarshkukreti** [comment]
That's really strange. The code builds for me on Ubuntu and macOS.

I'm using symlinks to files that are identical between reaml-preact and reaml-react, maybe that causes this error. I've now copied the files instead of creating symlinks. Could you please try again and see if it works for you?

**Comment by krausest** [comment]
That worked! Results have been [updated](https://krausest.github.io/js-framework-benchmark/current.html). Results are close to the js versions.

**Comment by utkarshkukreti** [comment]
Thanks!

**Comment by utkarshkukreti** [comment]
I see that the React benchmarks are mostly at version 16.8.6. What's the policy at updating the versions? The newest version is 16.13.0 now. Can I send a PR for that?

**Pull request merged**
