### PR TITLE
Add petit-dom

### PR DESCRIPTION
**Pull request by yelouafi**
https://github.com/yelouafi/petit-dom

### CODE REVIEW

**Comment by krausest** [comment]
@yelouafi Thank's - I plan to merge it the next few days.

**Comment by yelouafi** [comment]
No worry. Take your time. And thanks for this excellent repo

**Comment by krausest** [comment]
Thanks - results are [here](https://rawgit.com/krausest/js-framework-benchmark/0396cc6829531f3ac9cceed8c1c6423e18a7d200/webdriver-ts-results/table.html)

**Comment by yelouafi** [comment]
Nice! Thanks

**Pull request merged**
