### PR TITLE
Trying blazor-wasm .Net 5

### PR DESCRIPTION
**Pull request by aminya**
I have heard that a lot of work has been done to improve the performance of Blazor. I want to see if that makes a difference in this benchmark.

Requires sdk-installer from: https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2.md

### CODE REVIEW

**Comment by DuNuNuBatman** [comment]
I'm curious about this as well. Is there something else that needs to be done to merge this?

**Comment by aminya** [comment]
This PR is WIP and free for any one to pick. I don't think I can continue working on it.
Note that the Installation of .Net 5 requires custom script since it is not released yet.

**Comment by krausest** [comment]
PR looks good to me. I'll run it the next few days.

Regarding your issue: Can you open http://localhost:8080/frameworks/keyed/blazor-wasm/dist/wwwroot/index.html in a browser?

**Comment by aminya** [comment]
> PR looks good to me. I'll run it the next few days.
> 
> Regarding your issue: Can you open http://localhost:8080/frameworks/keyed/blazor-wasm/dist/wwwroot/index.html in a browser?

I did not know that I should first start the server in the root. Running `npm start` in the root solves the issue! I thought what it is described in number 4 of Readme is independent of number 1.
https://github.com/krausest/js-framework-benchmark#4-running-a-single-framework-with-the-automated-benchmark-driver

**Comment by aminya** [comment]
Here we go. The result is impressive. @dotnet 5 is much faster!! Around 2x in most of the tasks.

image

The result ran on on my TUF506IH (AMD 4800H) on Chrome 86. During running "clear rows" for dotnet 3 my laptop went to sleep, but the trend is clear.

**Comment by krausest** [comment]
Thanks. Here are the results:

**Comment by aminya** [comment]
I think I forgot to change the title. It is still saying v3.

**Comment by DuNuNuBatman** [comment]
Awesome, thanks for the quick update! 👍

**Pull request merged**
