### PR TITLE
Update cample to v3.2.0-alpha.7

### PR DESCRIPTION
**Pull request by antonmak1**
I think this will be 1.09 (I also committed a version there that improved the code a little)

### CODE REVIEW

**Comment by krausest** [comment]
Results will follow (most likely tomorrow).

**Comment by antonmak1** [comment]
> Results will follow (most likely tomorrow).

ok

**Comment by krausest** [comment]
Here's a comparison (updated keyed version on the left, old keyed version on the right):
Screenshot 2024-02-01 at 7 48 59 PM
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by antonmak1** [comment]
@krausest  For 7 months now, select row has been crap on the result, so I was sure that it would be 1.09, but in the end it’s 1.10. This is some kind of joke). Okay, this is all technically explained, so I will continue to try to find a solution for select row. Almost everything is perfect now, except create many rows and select row.

**Comment by antonmak1** [comment]
I'll write some code and try something new. I think now select row if I fix it, it won’t be far from 1.05.

**Comment by antonmak1** [comment]
@krausest Thank you very much for creating the results!

**Pull request merged**
