### PR TITLE
updated RE:DOM to v2.6.4

### PR DESCRIPTION
**Pull request by pakastin**
There was a small performance issue, which is now fixed (https://github.com/pakastin/redom/issues/71)

### CODE REVIEW

**Comment by pakastin** [comment]
Sorry for the conflict – I think `index.html` could be just removed from this PR and it will work..

**Comment by pakastin** [comment]
..if that's possible somehow..?

**Comment by krausest** [comment]
No problem - I'll take care of that.

**Comment by krausest** [comment]
It's faster - results are [here](https://rawgit.com/krausest/js-framework-benchmark/41ccdbacbc9bf7d4b9d02ea97dc2a542836c1d16/webdriver-ts-results/table.html)

**Comment by pakastin** [comment]
Wicked! 👌 RE:DOM non-keyed has (and had) the fastest startup time and keyed is number two! 😎

**Comment by krausest** [comment]
RE:DOM shows really a nice performance, but please note that the startup benchmark has a high variance, so please don't be too disappointed if next time hyperapp or surplus wins the startup benchmark ;-)

**Comment by pakastin** [comment]
Haha, no worries ;)

**Pull request merged**
