### PR TITLE
Bump to version 18

### PR DESCRIPTION
**Pull request by dmjio**
cc @krausest @sectore @FPtje @basvandijk @roelvandijk @luite
Updated to latest for benchmarks, if you can see any areas where performance can be improved in the  code below, please inform. 

Some updates:
  - Added `BangPatterns` pragma
  - Added ghcjs-options: `-DGHCJS_BROWSER -O2 -fspecialise-aggressively`
  - Removed extraneous event listeners, only `click` is needed.

Our largest bottlenecks are:
-  `partial update` [here](https://github.com/krausest/js-framework-benchmark/compare/master...dmjio:miso-v18?expand=1#diff-60a7cd9f582f1692a982a7c49fa1084bR140)
-  appending `1k` rows onto `10k` rows. Might be useful to step through `diff.js` for this.

### CODE REVIEW

**Comment by sectore** [comment]
@dmjio Great stuff! [`miso-0.18.0.0-keyed/src/Main.hs~`](https://github.com/dmjio/js-framework-benchmark/blob/679c09ee55c26d6346b759e6e20a00c1c26a38e0/miso-0.18.0.0-keyed/src/Main.hs%7E) might be slipped into this PR and can be deleted.

**Comment by dmjio** [comment]
@sectore done

**Comment by dmjio** [comment]
@krausest If there are regressions, do you still publish anyways?

**Comment by krausest** [comment]
Depends on what you mean. 
If you mean update the results table here in github - then yes, every time I merge a PR I update the results (unless I forget to). Anyways the results are inofficial in that sense that it‘s a possibly a mix of browser versions and OS versions.
I currently have no plans to publish a new official results round within the next few weeks.

If you want I can try miso-v18 and just put a screenshot of the results in here and you decide if you want it merged.

**Comment by krausest** [comment]
Here are the results - no regression:

bildschirmfoto 2018-04-04 um 20 55 15
bildschirmfoto 2018-04-04 um 20 55 28
bildschirmfoto 2018-04-04 um 20 55 38

Please let me know if it should be merged.

**Comment by dmjio** [comment]
Awesome! Thanks for doing this @krausest. Merge away!

**Pull request merged**
