### PR TITLE
Update cample to v3.2.0-beta.0

### PR DESCRIPTION
**Pull request by antonmak1**
Changed values. Now, select row should be at good speed

### CODE REVIEW

**Comment by krausest** [comment]
I'll post results here soon.

**Comment by antonmak1** [comment]
> I'll post results here soon.

Ty

**Comment by krausest** [comment]
Nice update!
Screenshot 2023-10-09 at 10 24 27 PM

**Comment by antonmak1** [comment]
> Nice update! Screenshot 2023-10-09 at 10 24 27 PM

Thanks a lot!

**Comment by antonmak1** [comment]
Thanks a lot!

**Pull request merged**
