### PR TITLE
Updated reflex benchs

### PR DESCRIPTION
**Pull request by zouloux**
# New reflex-atomic bench
This bench add some fine-grained updates to the diff. I created a new bench to check if it worth it.

# Updated reflex-js bench
The main has been updated.

### CODE REVIEW

**Comment by krausest** [comment]
I'm sorry, all PRs are currently blocked by https://github.com/krausest/js-framework-benchmark/issues/1655. Feel free to submit a PR for #1661 to get this PR merged 😄

**Comment by zouloux** [comment]
Understood

**Comment by krausest** [comment]
Thanks - I hope to publish results for the PR tomorrow.

**Comment by krausest** [comment]
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by zouloux** [comment]
Thanks 🎉

**Pull request merged**
