### PR TITLE
Update uhtml to version 3

### PR DESCRIPTION
**Pull request by WebReflection**
[µhtml](https://github.com/WebReflection/uhtml#readme) has landed with smaller size, modern code, and overall better performance, so I'd love to have it updated in here too, thank you 🙏

### CODE REVIEW

**Comment by krausest** [comment]
Thanks for the PR. Here's a comparison (both runs from today with playwright) - and I'm afraid to say the benchmark shows (almost?) no difference:
Screenshot from 2022-04-30 21-00-21

**Comment by WebReflection** [comment]
@krausest thanks for merging! The difference is bigger "*on my machine*" but the most noticeable is the startup metrics which, still "*on my machine*" is faster than solidjs. The size and logic has been simplified so it's faster overall, not just in this bench, yet it's weird your results are somehow different fro mine ... I'll post a screenshot tomorrow just for record sake.

**Comment by WebReflection** [comment]
This is what I see via Chromium 101.0.4951.41 and the **chrome100** branch.

It's not like day and light, but the difference is definitively more relevant than your results.
Also visible the startup metrics improvements ... but the test itself feels visibly faster with v3.

uhtml3

**Comment by krausest** [comment]
FWIW here's a screenshot from my MacBook Air:
Bildschirmfoto 2022-05-03 um 21 13 02
Bildschirmfoto 2022-05-03 um 21 15 43
Bildschirmfoto 2022-05-03 um 21 15 50

**Comment by WebReflection** [comment]
well, startup metrics score same as vanilla + smallest amount of bytes is something 🥳

thanks for the heads-up, I'm not even disappointed by these results 👍

**Pull request merged**
