### PR TITLE
Upgrade mimbl to 0.6.5.

### PR DESCRIPTION
**Pull request by mmichlin66**

### CODE REVIEW

**Comment by krausest** [comment]
Thanks. Here's a screenshot from the results:

**Comment by mmichlin66** [comment]
Hi Stefan,

I just saw the results for Chrome 108 and saw that my library Mimbl was marked with a new note 1139 – “Implementation uses runtime code generation”. I know that I don’t generate any code at runtime – could you explain or point me to an explanation on when you mark implementation with this note?

Thank you,
Michael Michlin

**Comment by fabiospampinato** [comment]
@mmichlin66 the bundled code probably includes an eval or Function call, probably injected by the bundler you are using. To get rid of the flag I think the bundled code should not include eval/Function calls, even if they are actually safe calls.

**Comment by krausest** [comment]
Please see https://github.com/krausest/js-framework-benchmark/issues/1139 for further discussion. Hope that explains it!

**Comment by mmichlin66** [comment]
Hi Stefan,

Thank you for answering. I searched the bundle’s code and couldn’t find any eval or Function construction calls, so not sure what action I can do to avoid it.

I will hopefully do a new revision soon and double check it again.

Regards,
Michael

**Comment by mmichlin66** [comment]
Hi Fabio,

Thank you for answering. I searched the bundle’s code and couldn’t find any eval or Function construction calls, so not sure what action I can do to avoid it.

I will hopefully do a new revision soon and double check it again.

Regards,
Michael

**Comment by krausest** [comment]
I'll take a look at it and get back soon (hopefully this weekend).

**Comment by krausest** [comment]
I raised #1148 for that

**Pull request merged**
