### PR TITLE
Add benchmark for Binding.scala

### PR DESCRIPTION
**Pull request by Atry**
Ping @mweststrate @trueadm

This is an interesting benchmark. Thanks to Binding.scala's [Precise data-binding](https://github.com/ThoughtWorksInc/Binding.scala#precise-data-binding) algorithm, all Binding.scala's delta operations are much faster than all other frameworks.

### CODE REVIEW

**Comment by Atry** [comment]
When I talking about delta operations, I means the benchmark `_03` `_04` `_05` `_06` `_08`.

**Comment by Atry** [comment]
Any feedback? @krausest

**Comment by krausest** [comment]
Thanks - results are [here](https://cdn.rawgit.com/krausest/js-framework-benchmark/097ee1c3fe15ee519af82ac1cb6e240d62a665f0/webdriver-ts/table.html)

**Comment by Atry** [comment]
There may be some wrong in the result. binding.scala-v10.0.1_06_remove-one-1k should not be that slow.

On my computer, binding.scala-v10.0.1_06_remove-one-1k is 10 times faster than vanillajs_06_remove-one-1k !

```
after initialized  06_remove-one-1k 0 binding.scala-v10.0.1
after run  06_remove-one-1k 0 binding.scala-v10.0.1
result binding.scala-v10.0.1_06_remove-one-1k [ { type: 'click', ts: 138156995841, dur: 348, end: 138156996189 },
  { type: 'paint', ts: 138157055751, dur: 1099, end: 138157056850 },
  { type: 'gc', ts: 138156900336, mem: 36.346763610839844 } ]
```

```
after initialized  06_remove-one-1k 0 vanillajs
after run  06_remove-one-1k 0 vanillajs
result vanillajs_06_remove-one-1k [ { type: 'click', ts: 138258041670, dur: 3743, end: 138258045413 },
  { type: 'paint', ts: 138258123467, dur: 1444, end: 138258124911 },
  { type: 'gc', ts: 138258135172, mem: 41.954978942871094 } ]
```

**Comment by yyx990803** [comment]
Wait what? I thought binding.Scala is (quote) *several times faster than Inferno and 4~20 times faster than Vue* (/quote)?

**Pull request merged**
