### PR TITLE
update preact -> 10.19.3

### PR DESCRIPTION
**Pull request by birkskyum**
updates preact-signals/-hooks/-classes and their the dev deps

### CODE REVIEW

**Comment by krausest** [comment]
Results will follow (most likely tomorrow).

**Comment by krausest** [comment]
I'd say no big change. Here's a comparison (updated keyed version on the left, old keyed version on the right):
Screenshot 2024-02-01 at 7 59 44 PM
[Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by birkskyum** [comment]
Wonder what happened to swap rows of preact-classes

**Comment by krausest** [comment]
You're right, I didn't look at it long enough.

Reported values for 10.19.3 for swap rows were: [168.313,167.961,170.203,168.297,170.521,171.66,167.849,169.46,166.491,170.407,169.428,170.801,168.257,171.381,170.89]
For 10.13.1 results were:
[23.054,23.37,23.41,23.355,25.367,23.622,23.137,22.424,23.67,22.818,22.743,22.533,22.872,22.273,22.571]
What a difference - looks like a big regression!

**Comment by birkskyum** [comment]
cc @developit

**Pull request merged**
