### PR TITLE
Dojo: Update to dojo 7 and fix non-keyed impl

### LINKED ISSUE #742: Fix dojo non-keyed
For some reason select row is broken for dojo in the non-keyed version.
Fixing the versions doesn't help.
@agubler Can you please take a look at it or should be just remove the non-keyed version?

### PR DESCRIPTION
**Pull request by agubler**
Fixes the non-keyed version of Dojo and also upgrades both version to the latest release (7.0.0).

cc @krausest 

With regards to https://github.com/krausest/js-framework-benchmark/issues/742#issuecomment-634919576, we are working on improving the core support in the rendering engine which hopefully will be available  soon. I tested a draft implementation with the keyed check and it passed so should resolve the issue.

Resolves #742

### CODE REVIEW

**Comment by krausest** [comment]
Sorry, the non-keyed version seems to have an issue with remove row.
When I click on the delete row button in one row it doesn't remove that row but the next one. Can you take a look at that please?

**Comment by agubler** [comment]
Oh that’ll teach me for not testing properly. Will do.

**Comment by agubler** [comment]
@krausest this should be updated now.

**Comment by krausest** [comment]
Thanks - that worked fine.  [Results](https://krausest.github.io/js-framework-benchmark/current.html) are updated.

**Comment by agubler** [comment]
Thanks @krausest, once we've fixed the move scenario for keyed, we'll probably remove the non keyed implementation.

**Pull request merged**
