### PR TITLE
Update cample to 3.2.0-alpha.15

### PR DESCRIPTION
**Pull request by antonmak1**
I think that it will no longer be 1.09, but will be somewhere around 1.06 - 1.07! Even if it’s 1.08, I think that it will be quite possible to finish up to 1.03 - 1.06 in the near future. I found a lot of stupid errors in the code, I think there will be more. I think I’ll finish it up to 1.03 - 1.06, although I see that I seem to have accelerated "select row" to almost maximum on the local machine, and the values are higher than others. In principle, I have almost completed the maximum of the framework. Maybe I’ll do a couple of PRs and we can say that the implementation will be ready. It will only be updated as new functionality is introduced, such as working with asynchronous data, etc.

P.S. Well, this time I’m not even 99.99999% sure, but 109% sure)

### CODE REVIEW

**Comment by krausest** [comment]
If all goes well I'll publish results tomorrow.

**Comment by antonmak1** [comment]
ok

**Comment by krausest** [comment]
Here's the comparison for the updated frameworks. On the left the new keyed version on the right the previous keyed version. 
With the exception of vue-pinia all results including vanillajs were slower than in the full run. I haven't any proof yet, but it seems to me that security patches after a major update can cause some slowdown for the benchmark.
So cample might have improved more than the 0.1 improvement sugest.
Screenshot 2024-03-05 at 08 11 36

**Comment by antonmak1** [comment]
OK. Well, now the result is 1.09 at least.

**Pull request merged**
