### PR TITLE
feat: add vue-jsx-vapor

### PR DESCRIPTION
**Pull request by zhiyuanzmj**
Vue JSX Vapor mode. Use same IR generator and runtime with Vue Vapor.

### CODE REVIEW

**Comment by krausest** [comment]
I tried to build before leaving for holidays. But it fails with the following error:
```
npm run rebuild-ci keyed/vue-jsx-vapor

> js-framework-benchmark@1.0.0 rebuild-ci
> node cli.js rebuild-single --ci -f keyed/vue-jsx-vapor

Rebuild single: ci true frameworks [ 'keyed/vue-jsx-vapor' ]
Rebuild build single: useCi true frameworks [ 'keyed/vue-jsx-vapor' ]
Deleted: yarn-lock,dist,elm-stuff,bower_components,node_modules,output
npm ci

added 89 packages, and audited 90 packages in 2s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm run build-prod

> js-framework-benchmark-vue-jsx-vapor@1.0.0 build-prod
> vite build

failed to load config from /home/stefan/js-framework-benchmark/frameworks/keyed/vue-jsx-vapor/vite.config.js
error during build:
SyntaxError: Unexpected token 'with'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:273:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
ERROR: Rebuilding  keyed/vue-jsx-vapor was not successful
```
Can you take a look at it? I'll try to merge it in September when I'm back.

**Comment by zhiyuanzmj** [comment]
Fixed.

**Comment by krausest** [comment]
Thanks. Please allow me a few days to merge all PRs and publish an update.

**Comment by krausest** [comment]
Here are the results (left updated or added implementations, on the right last results if available):
Screenshot 2024-09-06 at 16 49 11

As one can see from vanillajs the run wasn't very good (though on AC, indexing off, but without rebooting) so I'd expect faster results for the next full run.

**Comment by zhiyuanzmj** [comment]
Thanks!

**Pull request merged**
