### PR TITLE
ci: test Windows

### PR DESCRIPTION
**Pull request by DanielRuf**
TravisCI has now support for Windows so we can also test there.

See https://blog.travis-ci.com/2018-10-11-windows-early-release

This PR is meant to be WIP as we have to check what we have to adjust in the CI config to get it running there too.

### CODE REVIEW

**Comment by alexfmpe** [comment]
Tried getting appveyor builds a while back but IIRC there was one framework that wouldn't work
See https://github.com/krausest/js-framework-benchmark/pull/386

**Comment by DanielRuf** [comment]
As TravisCI is not used anymore I'll close this PR. in general TravisCI supports macOS, Linux and Windows. This would not require 2 platforms.

The Windows issue can be checked and probably solved.

**Comment by alexfmpe** [comment]
Yeah there was a linux/mac Travis CI a ways back, but with a 1h timeout (whereas circleci had 5) - had to split the build into lots of jobs which increased the total time due to booting them all up. Might be more forgiving nowadays.

**Comment by DanielRuf** [comment]
Here is a current overview for TravisCI environments: https://docs.travis-ci.com/user/reference/overview/

**Pull request closed without merging**
