### PR TITLE
Update hyperapp to current v1.2.0

### PR DESCRIPTION
**Pull request by mhoyer**
I just updated to currently latest version of hyperapp.

### CODE REVIEW

**Comment by SkaterDad** [comment]
@mhoyer Hyperapp v1.2 is released now.  Could you update this PR?  The same application code should work.

**Comment by mhoyer** [comment]
@SkaterDad So I did!

**Comment by krausest** [comment]
Ah - and in between I merged 1.1.2...
I'll update the next few days to 1.2.0

**Comment by krausest** [comment]
Nevertheless - the results for 1.1.2 are [here](https://www.rawgit.com/krausest/js-framework-benchmark/802a2ccf15857ef89ea0f5f7be6b88afab72b8fa/webdriver-ts-results/table.html)
Maybe 1.2 looks better.

**Comment by krausest** [comment]
Results for 1.2 are [here](https://www.rawgit.com/krausest/js-framework-benchmark/d5ebaf542204d1511b9f5f38d76380c9c506c53e/webdriver-ts-results/table.html). The relevant part:
bildschirmfoto 2018-03-20 um 07 49 50

**Comment by mhoyer** [comment]
Perfect. Thank you.

**Pull request merged**
