### PR TITLE
udomsay - a vDOM-less JSX & signals based library

### PR DESCRIPTION
**Pull request by WebReflection**
While I am still working on some possible performance improvements I am already pretty happy about the current [udomsay](https://github.com/WebReflection/udomsay#readme) result and I'd love to see it as part of the table, where the goal is to compete with other JSX based implementations in terms of memory consumption, code size and, after all, raw performance.

Thank you in advance for considering this addiction.

udomsay

### CODE REVIEW

**Comment by WebReflection** [comment]
P.S. if curious, this is the current result locally.

udomsay-v0 1 5

**Comment by WebReflection** [comment]
P.S. I've made some change to allow non-keyed benchmark to run as well.

**Comment by WebReflection** [comment]
FYI - I've flagged the module as 772 because I believe taking the signal off the whole App and using classList to add/remove danger is 772 ... even if the code is still idiomatic as it uses a signal to update the view (off main logic, like solid-js does) ... although it doesn't use an ad-hoc utility, it just effect a part from the `<App />`.

I am not planning to make any other change now so please consider running and merging this version.

Happy to change anything that needs changes though.

**Comment by WebReflection** [comment]
updated the non-keyed too 😅

**Comment by krausest** [comment]
Thanks. Here's the comparison and it looks much better for select row than yours (did you change something about it?):
Bildschirm­foto 2022-10-29 um 21 25 49
Please note that this was an incremental run, only updated frameworks and vanillajs were run. And at least vanillajs had a pretty bad run. It's currently hard to say if this is due to the recent chrome bugfix in 107 or just a bad run.

**Comment by WebReflection** [comment]
@krausest I've epxlained in here: https://github.com/krausest/js-framework-benchmark/pull/1127#issuecomment-1293249167

I've change the logic and added 772 as *issue* because I felt stupid not using off-logic signal to handle the single selected row like solid-js does (or others) but there's no ad-hoc utility which is why 772 is flagged as issue ... it's all good, your run looks fine to me.

**Pull request merged**
