### PR TITLE
maquette-v3.0.1-keyed

### PR DESCRIPTION
**Pull request by leeoniya**
addresses https://github.com/krausest/js-framework-benchmark/issues/270

I did a pretty straightforward port of domvm. considering that the only optimization is event delegation, it performs pretty well. i couldn't find a way to make maquette swallow a non-keyed impl; it bitches at runtime about needing keys when it detects similar sibling nodes.

this impl may need slight tweaking, since i just took the UMD build and dumped it into `/src`. i added it to `package.json` but didnt bother working out exactly how to require/import it from there.

maquette-keyed

### CODE REVIEW

**Comment by krausest** [comment]
Sorry - I'm getting an exception when clicking "create 1,000 rows":
Uncaught ReferenceError: getProjection is not defined
    at HTMLButtonElement.<anonymous> (bundle.js:1)
Any idea how to fix it?

**Comment by leeoniya** [comment]
@johan-gorter

> By the way, I somehow had to disable uglify in build.js, because it created errors at runtime (getProjection was undefined).

https://github.com/krausest/js-framework-benchmark/issues/270#issuecomment-342976549

**Comment by johan-gorter** [comment]
One more remark about this pull request, could you please include maquette from node_modules instead of the copy that is inlined. This will enable me to try out new approaches using `npm link`. @leeoniya will you update this pull request or shall I start my own?

**Comment by leeoniya** [comment]
yeah, just make a new pr. i'll close this one rather than having to maintain it.

**Pull request closed without merging**
