### PR TITLE
feat: add sonnetjs

### PR DESCRIPTION
**Pull request by htmujahid**
Sonnet js is an opinionated framework for writing clean and organized JavaScript code. It provides different features out of the box with vanilla javascript:

1. SSR
2. Routing
3. Global Store

Here is official site of sonnetjs [sonnetjs](https://sonnet.js.org), [repo](https://github.com/sonnetjs/sonnet)

### CODE REVIEW

**Comment by krausest** [comment]
I'm sorry it doesn't work. In the version you provided no Main.js is created in the dist directory. The build process says:
```
<script src="src/Main.js"> in "/index.html" can't be bundled without type="module" attribute
```
Can you please take a look at it?

**Comment by htmujahid** [comment]
@krausest fixed this stuff

**Comment by htmujahid** [comment]
Sorry for issues. 
I have fixed that in this build

**Comment by htmujahid** [comment]
@krausest any udpate on this

**Comment by krausest** [comment]
Sorry, I was busy with getting chrome 126 results out.
Here's a preview of the results. Please note that vanillajs was slower than in the chrome 126 run, so it might score well in a full run!
Screenshot 2024-06-15 at 21 49 07

**Comment by krausest** [comment]
JFI: We added #772 to sonnet due to direct dom manipulation.

**Pull request merged**
