### PR TITLE
add missing measurements with console-output

### PR DESCRIPTION
**Pull request by mindplay-dk**
Other benchmarks show an approximate measurement in the browser console - this one didn't.

### CODE REVIEW

**Comment by ryansolid** [comment]
Yeah, I was wondering where we stand on this. Almost none of the top 30 implementations actually use the console.log, just to cleanup code and reduce the tiniest overhead. I just stopped adding it to implementations I've done. Does anyone have an opinion on this?

**Comment by leeoniya** [comment]
we should drop them entirely. in the best case they're still wrong.

**Comment by krausest** [comment]
I tried to clarify that in the rules
https://github.com/krausest/js-framework-benchmark/commit/af98c85b40c90b6abf06ecc1bd8a6d3f8f287fc5
I want to keep it in the vanillajs implementation, but it can be dropped anywhere else. It serves as a sanity check for me whenever the next chrome version yields weird results (as it regularly does). 
@mindplay-dk Thus I'm closing this PR.

**Comment by mindplay-dk** [comment]
Yeah, it's totally unreliable of course, I agree - just copy/pasting that into every benchmark is obviously not the right approach...

(I mostly did it because I couldn't get the real benchmark to run - but I understand from your answer in #651 that's because I need to upgrade node to v10...)

**Pull request closed without merging**
