### PR TITLE
keyed/preact: update preact to 10.5.2

### PR DESCRIPTION
**Pull request by utkarshkukreti**
I'm seeing some impressive improvements: in my local run, the slowdown before this PR = 1.34, after = 1.26!

### CODE REVIEW

**Comment by utkarshkukreti** [comment]
Pushed an update to switch to [React's new jsx-runtime](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) (which Preact already supports in 10.5.2). The slowdown went from 1.26 to 1.22!

**Comment by utkarshkukreti** [comment]
(The slowdowns are on my system which seems to be running vanilla much slower than the results in current.html.)

**Comment by utkarshkukreti** [comment]
I also updated Preact on keyed/reaml-preact to 10.5.2. I hope that's fine to do in the same PR.

**Comment by krausest** [comment]
Thanks. Indeed a bit faster. Here are the new results:

And for reference the old results:

**Pull request merged**
