### PR TITLE
Update to Marko 5

### PR DESCRIPTION
**Pull request by birkskyum**
I've managed to make a Marko 5 version using using Marko Run.

It appears to be noticeably slower than Marko 4.

@DylanPiercey - Is that an unexpected result? Can you see something I didn't do in a non-optimal way?

Screenshot 2023-10-19 at 23 42 20

### CODE REVIEW

**Comment by DylanPiercey** [comment]
@birkskyum firstly thanks for doing this!

Just glancing at the code here, it appears that Marko is running in debug mode which would impact performance.
As it stands Marko is only bundled in production mode if you set `NODE_ENV=production` while bundling.

This is a bit strange and probably something we'll change once we come around to it.

**Comment by birkskyum** [comment]
Can I set this in Vite config?

**Comment by DylanPiercey** [comment]
@birkskyum I believe that should work. If not you could just update the `build-prod` command to prefix with `NODE_ENV=production` (which we probably need to do on our examples 😓 )

**Comment by birkskyum** [comment]
That did seem to help a bit, but there is still an overhead.

Screenshot 2023-10-20 at 00 19 04

**Comment by DylanPiercey** [comment]
👍 that's possibly accurate. Thanks for the ping!

**Pull request merged**
