### PR TITLE
Update Strve to v6.2.0

### PR DESCRIPTION
**Pull request by maomincoding**
Strve.js v6.2.0 is released! 

[https://github.com/strveJs](https://github.com/strveJs)

### CODE REVIEW

**Comment by maomincoding** [comment]
Thanks for the hard work, author.

**Comment by maomincoding** [comment]
Hello~ Can this branch be merged? thanks！ @krausest

**Comment by krausest** [comment]
... except that your implementation isn't working as advertised:
```
npm run isKeyed -- --headless true keyed/strve
...
Keyed test for swap failed. Expected at least 1 added and 1 removed TR, but there were 0 added and 0 removed
Keyed test for create rows failed. Expected that 1000 TRs should be removed and added, but there were 0 added TRs and 0 were removed
Keyed test for remove failed. Expected that the dom node for the 2nd row would be removed, but it wasn't
strve-v6.2.0-keyed is non-keyed for 'run benchmark' and non-keyed for 'remove row benchmark' and non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
ERROR: Framework strve-v6.2.0-keyed is not correctly categorized
```
Should we move it to the non-keyed section?

**Comment by maomincoding** [comment]
I will pull down the code and retest it

**Comment by maomincoding** [comment]
The test results on my end are the same as yours. I will re release the PR on my end. Thank you！

**Comment by maomincoding** [comment]
My ultimate expected outcome is in keyed.

**Pull request closed without merging**
