### PR TITLE
Adding fidan-v0.0.12-keyed

### PR DESCRIPTION
**Pull request by ismail-codar**
Under development [fidan](https://github.com/ismail-codar/fidan) is quite innovative. Benchmarks are works fine and generally fast.  But there is an issue: https://github.com/krausest/js-framework-benchmark/issues/549

### CODE REVIEW

**Comment by krausest** [comment]
A big thanks for spotting this issue and reporting it!
I took a look at fidan. I'm afraid to say it's currently not properly keyed for replace rows:
```
Stefans-MBP:webdriver-ts stefan$ npm run isKeyed -- --framework fidan

> webdriver-ts@1.0.0 isKeyed /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js "--framework" "fidan"

Frameworks that will be checked fidan-v0.0.6-keyed
fidan-v0.0.6-keyed is non-keyed for 'run benchmark' and keyed for 'remove row benchmark' keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
```
It currently recycles the rows when replacing all rows (you can easily check if you change the background-color for a row with the devtools. Then replace all rows. The background color is still there). This is allowed for non-keyed frameworks, but not for keyed.

**Comment by ismail-codar** [comment]
Yeah, that's my fault. I just added `renderMode: "reconcile"` option for array rendering. 
https://github.com/krausest/js-framework-benchmark/pull/551/files#diff-163024d903e225a027d6060c95904ccbR225 So reconcile function given from stage0 thanks for ivi, surplus, stage0 authors.

**Comment by krausest** [comment]
Thanks - looks correctly keyed now. Results have been updated. Here's a screenshot:
Bildschirmfoto 2019-04-22 um 18 36 32

**Comment by ismail-codar** [comment]
Thanks.

**Pull request merged**
