### PR TITLE
Adding Fast framework (https://www.fast.design/)

### PR DESCRIPTION
**Pull request by dsvorc41**
This PR adds benchmarks for Fast framework https://www.fast.design/, 
as well as additional documentation on how to add new implementations/frameworks
in the future

It also adds a demo (GIF) to show how the benchmark app is supposed to look like and behave:
demo

Comparing Vanilla JS vs Fast vs React:

Screenshot 2023-10-03 111243

Screenshot 2023-10-03 111359

### CODE REVIEW

**Comment by krausest** [comment]
Sorry, the `npm run isKeyed` test fails:
```
Keyed test for swap failed. Expected at least 1 added and 1 removed TR, but there were 0 added and 0 removed
Keyed test for create rows failed. Expected that 1000 TRs should be removed and added, but there were 0 added TRs and 0 were removed
fast-v2.0.0-beta.26-keyed is non-keyed for 'run benchmark' and keyed for 'remove row benchmark' and non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
ERROR: Framework fast-v2.0.0-beta.26-keyed is not correctly categorized
```
Seems like swap doesn't actually swap the DOM nodes and create recycles the rows. If so it must be categorized as non-keyed.

**Comment by dsvorc41** [comment]
Thank you! Can you add a bit more info please? I read the docs, but I still don't quite understand the difference between `keyed` and `non-keyed`.

**Comment by dsvorc41** [comment]
Oh, I think I understand the difference now:

This is keyed/vanillajs:
```
  swapRows() {
    if (this.data.length > 10) {
      this.store.swapRows();
      this.data[1] = this.store.data[1];
      this.data[998] = this.store.data[998];

      this.tbody.insertBefore(this.rows[998], this.rows[2]);
      this.tbody.insertBefore(this.rows[1], this.rows[999]);

      let tmp = this.rows[998];
      this.rows[998] = this.rows[1];
      this.rows[1] = tmp;
    }
  }
```

And this is non-keyed/vanillajs:
```
  swapRows() {
    let old_selection = this.store.selected;
    this.store.swapRows();
    this.updateRows();
    this.unselect();
    ...
  }
  
  ...
  
  updateRows() {
    for (let i = 0; i < this.rows.length; i++) {
      if (this.data[i] !== this.store.data[i]) {
        let tr = this.rows[i];
        let data = this.store.data[i];
        tr.data_id = data.id;
        tr.childNodes[0].innerText = data.id;
        tr.childNodes[1].childNodes[0].innerText = data.label;
        this.data[i] = this.store.data[i];
      }
    }
  }
    ```
Based on the code examples, it seems that `keyed` implementation is replacing the entire `tr` element each time it's content changes, while `non-keyed` implementation reuses the existing `tr` element but changes its `innerText` and other attributes. 

Is my observation correct? The only difference is in reusing existing elements and replacing them with new elements?

**Comment by dsvorc41** [comment]
@krausest I moved my implementation into `non-keyed` folder. Thank you!

**Comment by dsvorc41** [comment]
Hi! @krausest do you have any updates on this PR? Thanks!

**Comment by krausest** [comment]
I'll post results here soon.

**Comment by dsvorc41** [comment]
Thank you! I'm really interested to see the full results. Thanks!

**Comment by krausest** [comment]
Ah sorry, it‘s now contained in the results:
https://krausest.github.io/js-framework-benchmark/current.html

**Pull request merged**
