### PR TITLE
Update san

### PR DESCRIPTION
**Pull request by errorrik**
The following changes has been made:

- update san version to 3.7.3
- add keyed test
- update swap and select implementation of non-keyed

### CODE REVIEW

**Comment by krausest** [comment]
Great - a keyed version (and the keyed got faster too). Results have been updated:
Bildschirmfoto 2019-04-11 um 20 58 23

**Comment by errorrik** [comment]
Thank you @krausest .

And, how about non-keyed?

**Comment by krausest** [comment]
Should be published in the result table:
https://krausest.github.io/js-framework-benchmark/current.html

**Comment by errorrik** [comment]
(*˘︶˘*).｡.:*♡

**Pull request merged**
