### PR TITLE
Add HyperApp v0.6.0 benchmarks.

### PR DESCRIPTION
**Pull request by jbucaran**
@krausest @leeoniya 

Add HyperApp ~v0.5.0~ *v0.6.0* benchmarks.

screen shot 2017-02-28 at 5 48 59

* https://github.com/hyperapp/hyperapp/issues/75

### CODE REVIEW

**Comment by jbucaran** [comment]
@krausest Here is the PR.

**Comment by krausest** [comment]
Thanks - I'll merge when I'm back from holidays in about a week.

**Comment by leeoniya** [comment]
there's a small bug in this impl.

when a row is deleted, any selected row is deselected.

**Comment by jbucaran** [comment]
@leeoniya Thanks for noticing. Pushed a fix for hyperapp and choo, whose implementation I used to create hyperapp's.

**Comment by jbucaran** [comment]
@krausest Thanks! I'm in the process of updating HyperApp again and there were some speed gains. What should I do in this case?

A PR with the new version or overwrite the current version? 👋

**Comment by leeoniya** [comment]
overwrite.

unless the general public has an interest in an older version (eg existing large install base).

**Comment by jbucaran** [comment]
@leeoniya Thanks, I'll do that then when the new version is out.

**Comment by krausest** [comment]
Results on my machine are [here](https://rawgit.com/krausest/js-framework-benchmark/7e0b90971f7c184e9aad361cd1e49e29b6dcd898/webdriver-ts/table.html)

**Pull request merged**
