### PR TITLE
Updated react to react16.0.0 in react-redux package

### PR DESCRIPTION
**Pull request by rajsek**
Hi all,
I have updated the react-redux package to use react 16.0.0.

### CODE REVIEW

**Comment by rajsek** [comment]
Hi All,
This is my first pull request, can i resolve the conflicting in `webdriver-ts/table.html` or do i need to wait for contributor instruction?

Thanks and Regards,
D.Raja Sekar

**Comment by krausest** [comment]
@rajsek Thanks for asking. Please just leave it – I‘ll merge it the next few days. It‘s easier not to commit any result file as I‘m going to update them after merging. I‘ll add that to the Readme.

**Comment by krausest** [comment]
Just tried to merge - but I noticed that selecting rows doesn't work anymore. Can you take a look at it?

**Comment by rajsek** [comment]
Hi Stefan,

Fixed that issue and pushed to remote :).
Please have a look and accept my pull request.

Thanks,
Rajsek

**Comment by rajsek** [comment]
Thanks krausest...
I like to know about the tentative timeline when will be the react 16 change reflect in actual benchmark site.. 

Thanks,
Rajsek

**Comment by krausest** [comment]
[Now](https://www.rawgit.com/krausest/js-framework-benchmark/8056530b6907f0933e5213c4cc9884cc31d94ad5/webdriver-ts-results/table.html) ;-)

**Pull request merged**
